import { Property, PropertyType } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    title: '2 Bedroom House',
    type: PropertyType.RENT,
    price: 900,
    location: 'Agbogba, Last Stop',
    description: 'Cozy 2 bedroom house available for rent immediately.',
    bedrooms: 2,
    image: 'https://picsum.photos/seed/pama1/600/400',
    driveToViewPrice: 50,
  },
  {
    id: 'p2',
    title: '3 Bedroom House',
    type: PropertyType.SALE,
    price: 2000000,
    location: 'Ashongman Estate',
    description: 'Luxurious 3 bedroom house in a prime estate location.',
    bedrooms: 3,
    image: 'https://picsum.photos/seed/pama2/600/400',
    driveToViewPrice: 50,
  },
  {
    id: 'p3',
    title: '6 Bedroom House',
    type: PropertyType.SALE,
    price: 6000000,
    location: 'Oyarifa, Pantang Junction',
    description: 'Massive 6 bedroom family home with modern amenities.',
    bedrooms: 6,
    image: 'https://picsum.photos/seed/pama3/600/400',
    driveToViewPrice: 50,
  },
  {
    id: 'p4',
    title: '3 Bedroom Apartment',
    type: PropertyType.RENT,
    price: 1500,
    location: 'Adenta, Frafraha',
    description: 'Modern apartment in a secure complex.',
    bedrooms: 3,
    image: 'https://picsum.photos/seed/pama4/600/400',
    driveToViewPrice: 50,
  },
  {
    id: 'p5',
    title: '5 Bedroom House',
    type: PropertyType.SALE,
    price: 9000000,
    location: 'East Legon',
    description: 'Premium property with large compound in East Legon.',
    bedrooms: 5,
    image: 'https://picsum.photos/seed/pama5/600/400',
    driveToViewPrice: 50,
  },
  {
    id: 'p6',
    title: '500SqM Land',
    type: PropertyType.SALE,
    price: 12100,
    location: 'Nigeria, Odeomi',
    description: 'Prime land available for development.',
    areaSize: '500 SqM',
    image: 'https://picsum.photos/seed/pama6/600/400',
    driveToViewPrice: 100,
  },
  {
    id: 'p7',
    title: '464SqM Land',
    type: PropertyType.SALE,
    price: 45400,
    location: 'Nigeria, Calabar',
    description: 'Installment payment plans available.',
    areaSize: '464 SqM',
    image: 'https://picsum.photos/seed/pama7/600/400',
    driveToViewPrice: 100,
  },
  {
    id: 'p8',
    title: '2 Bedroom House',
    type: PropertyType.SALE,
    price: 1240800,
    location: 'Spintex, Com. 18',
    description: 'Newly built 2 bedroom house in Spintex.',
    bedrooms: 2,
    image: 'https://picsum.photos/seed/pama8/600/400',
    driveToViewPrice: 50,
  },
  {
    id: 'p9',
    title: '5 Bedroom House',
    type: PropertyType.SALE,
    price: 6979500,
    location: 'Spintex',
    description: 'Spacious rooms, 5 minutes drive to the Airport.',
    bedrooms: 5,
    image: 'https://picsum.photos/seed/pama9/600/400',
    driveToViewPrice: 50,
  },
];

export const REGIONS = ['Accra', 'Eastern', 'Central', 'Ashanti', 'Other'];
export const TOWNS = ['Adenta', 'Agbogba', 'Akatsi-Abor', 'Ashonman', 'Botwe', 'Kwabenya', 'East Legon', 'Madina', 'Oyarifa', 'Other'];