export interface Student {
  id: string;
  name: string;
  nationality: string;
  programme: string;
  level: string;
  sem: string;
  type: 'Degree' | 'Diploma' | 'Certificate';
  department: string;
}

export const departments = [
  { short: 'FDT', name: 'Fashion Design Technology', students: 63, degree: 35, diploma: 0, cert: 28 },
  { short: 'JDT', name: 'Jewellery Design Technology', students: 17, degree: 11, diploma: 4, cert: 2 },
  { short: 'DMCD', name: 'Digital Media & Communication Design', students: 43, degree: 32, diploma: 0, cert: 11 },
  { short: 'PDE', name: 'Product Design & Entrepreneurship', students: 5, degree: 2, diploma: 1, cert: 2 },
];

export const students: Student[] = [
  // FDT
  { name: 'Roselyn Etsa Kumashie', id: '100156', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Naomi Obeng', id: '100153', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Hester Amponsah Asamoah', id: '100161', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Alhasum Louisa Owusua', id: '100136', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Thelma Atsu', id: '100142', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Elizabeth Amewugah', id: '100138', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Awuye Venoria Delali', id: '100174', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Boatemaa Erica', id: '100177', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Leticia Tetteh', id: '100176', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Esther Acquah Ansah', id: '100117', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Michaella Akorfa Amerworwor', id: '100121', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Sarah Adjorko Akuetteh-klu', id: '100127', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Samuel Baffour Ahenkorah Armah', id: '100128', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Queen Assibi Siebik', id: '100116', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Abigail Tamakloe', id: '100125', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '100', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Juliana Awafu', id: '100100', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '200', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Ileen Naa Kwarley Titus-Glover', id: '100098', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '200', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Alberta Kpogli', id: '100107', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '200', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Keziah Yayra Goku', id: '100102', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '200', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Josephine Asantewaa Offei', id: '100088', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '200', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Mrs. Evelyn Adupong Fosu', id: '100099', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '200', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Rita Siame', id: '100051', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '300', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Owusua Jessica', id: '100053', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '300', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Paula Elorm Dowoli', id: '100056', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '300', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Ellen Ohenewaa Botwe', id: '100075', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '300', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Gifty Lovely Nagmanja', id: '100039', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '300', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Miriam Elikem Amegbletor', id: '100038', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '300', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Justice Delanyo Dogbe', id: '100037', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '300', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Winnifred Washington', id: '100040', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '300', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Gbande Stephen', id: '100137', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '300', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Sharon Newman', id: '100094', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '400', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Precious Adjo Akpalu', id: '100023', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '400', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Mary Bebaa Sah', id: '100011', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '400', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Issah Nurudeen Nuru', id: '100013', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '400', sem: '1', type: 'Degree', department: 'FDT' },
  { name: 'Kiana Obeng-Fosu', id: '100007', nationality: 'Ghanaian', programme: 'B.Tech Fashion Design Technology', level: '400', sem: '2', type: 'Degree', department: 'FDT' },
  { name: 'Janet Yeboah Yayra', id: '100166', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Princess Korkor', id: '100149', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Gifty Dziedzorm Jably', id: '100165', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Beatrice Binney', id: '100146', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Jemimah Klenam Adamaley', id: '100155', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Victoria Mawunyo Abla Kudoh', id: '100154', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Ruth Bese', id: '100170', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Mabel Dede Ahingo Sackitey', id: '100171', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Borketey Selina Borkor', id: '100172', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Ruth Etornam Ahiable', id: '100173', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Nida Korkor Debrah', id: '100175', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.1', sem: '1', type: 'Certificate', department: 'FDT' },
  { name: 'Gifty Adobasam', id: '100119', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Albert Adja Torgbor', id: '100138', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Gladys Akua Aggrey', id: '100126', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Priscilla Amoah', id: '100120', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Ruth Bilson', id: '100115', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Jennifer Yayra Dzakpasu', id: '100132', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Paul Kelechi', id: '100122', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Josephine Akua Kwao', id: '100114', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Elizabeth Namateng Sorni', id: '100130', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Gloria Tsatsu', id: '100131', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Cert.2', sem: '2', type: 'Certificate', department: 'FDT' },
  { name: 'Miriam Aseda Raleigh', id: '100110', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'FDT' },
  { name: 'Gifty Mawusi Sallah', id: '100096', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'FDT' },
  { name: 'Fuseina Sumaila', id: '100092', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'FDT' },
  { name: 'Tracy Egwuenu Kolese', id: '100093', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'FDT' },
  { name: 'Patricia Selasi Mensah', id: '100091', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'FDT' },
  { name: 'Miriam Karkie Akuaku', id: '100085', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'FDT' },
  { name: 'Felicia Annor Dansoa', id: '100103', nationality: 'Ghanaian', programme: 'Certificate in Fashion Design Technology', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'FDT' },

  // JDT
  { name: 'Gold Akosua Adeyemo', id: '100160', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '100', sem: '1', type: 'Degree', department: 'JDT' },
  { name: 'Basil Kpabi Nyarko', id: '100141', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '100', sem: '1', type: 'Degree', department: 'JDT' },
  { name: 'Cynthia Wornyo', id: '100159', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '100', sem: '1', type: 'Degree', department: 'JDT' },
  { name: 'Solomon Bamfo Akoto', id: '100133', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '100', sem: '2', type: 'Degree', department: 'JDT' },
  { name: 'Solomon Boamah Acheampong', id: '100049', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '300', sem: '1', type: 'Degree', department: 'JDT' },
  { name: 'Erica Eyram Amevor', id: '100059', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '300', sem: '1', type: 'Degree', department: 'JDT' },
  { name: 'Samuel Nii Antiea Quarshie', id: '100062', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '300', sem: '1', type: 'Degree', department: 'JDT' },
  { name: 'Mawuenam Amenyedzi', id: '100074', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '300', sem: '1', type: 'Degree', department: 'JDT' },
  { name: 'Caleb Adjei Akpor', id: '100061', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '300', sem: '1', type: 'Degree', department: 'JDT' },
  { name: 'Georgina Addai Sarfo', id: '100035', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '300', sem: '2', type: 'Degree', department: 'JDT' },
  { name: 'Felicia Amponsah Agyei', id: '100109', nationality: 'Ghanaian', programme: 'BA Jewellery Design Technology', level: '400', sem: '1', type: 'Degree', department: 'JDT' },
  { name: 'Naafia Gyamfi Poku', id: '100145', nationality: 'Ghanaian', programme: 'Diploma In Jewellery Design', level: '100', sem: '1', type: 'Diploma', department: 'JDT' },
  { name: 'Kwame Boateng Agyekum', id: '100152', nationality: 'Ghanaian', programme: 'Diploma In Jewellery Design', level: '100', sem: '1', type: 'Diploma', department: 'JDT' },
  { name: 'Glenn Moo Mbaya', id: '100158', nationality: 'Ghanaian', programme: 'Diploma In Jewellery Design', level: '100', sem: '1', type: 'Diploma', department: 'JDT' },
  { name: 'Francisca Ama Semavor', id: '100110', nationality: 'Ghanaian', programme: 'Diploma In Jewellery Design', level: '200', sem: '1', type: 'Diploma', department: 'JDT' },
  { name: 'Afua Dei-Tutu Bright', id: '100123', nationality: 'Ghanaian', programme: 'Certificate in Bench Jewellery', level: 'Cert.', sem: '2', type: 'Certificate', department: 'JDT' },
  { name: 'Seth Sedo Tsatsu', id: '100113', nationality: 'Ghanaian', programme: 'Certificate in Bench Jewellery', level: 'Cert.', sem: '2', type: 'Certificate', department: 'JDT' },

  // DMCD
  { name: 'Adam Alphonso Sannoh', id: '100168', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '100', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Michael Tettey', id: '100148', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '100', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Samuel Larbi', id: '100140', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '100', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Enoch Nkansah Appianing', id: '100162', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '100', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Prosper Mawufemor Amehlor', id: '100164', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '100', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Lokko Glenn Deladem', id: '100151', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '100', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Esther Appiah', id: '100157', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '100', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'William Abbey', id: '100112', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '100', sem: '2', type: 'Degree', department: 'DMCD' },
  { name: 'Joseph Kwarteng', id: '100134', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '100', sem: '2', type: 'Degree', department: 'DMCD' },
  { name: 'Samuel Mensah Boakye', id: '100101', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '200', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Francisca Gumenu', id: '100084', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '200', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Abotsi Joshua Mawulikem', id: '100090', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '200', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Abena Nyadu', id: '100108', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '200', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Alfred Kodua Bram', id: '100087', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '200', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Prince Elikem Ekpe', id: '100083', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '200', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Joseph Yeboah', id: '100052', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '300', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Cornelius Boateng', id: '100054', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '300', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Fati Adamu Seidu', id: '100055', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '300', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Muniratu Awalker', id: '100057', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '300', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Lydia Xorlali Ocloo', id: '100066', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '300', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Francis Bonney', id: '100068', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '300', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Robert Abbey Lomo-Tettey', id: '100042', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '300', sem: '2', type: 'Degree', department: 'DMCD' },
  { name: 'David Djorbua Teye', id: '100015', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '300', sem: '2', type: 'Degree', department: 'DMCD' },
  { name: 'Luggard Buabin Awuah', id: '100020', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '400', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Dennis Nene Adjatey Dumanya', id: '100010', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '400', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Vincent Apladey', id: '100026', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '400', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Jonathan Otokunor Sackey', id: '100014', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '400', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Bismark Boateng Mensah', id: '100021', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '400', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Daniel Yesuflem Adzande', id: '100024', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '400', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Dominic Osemen Elijah', id: '100025', nationality: 'Nigerian', programme: 'BTech Digital Media & Communication Des.', level: '400', sem: '1', type: 'Degree', department: 'DMCD' },
  { name: 'Twenefour Bettina Saamea', id: '100008', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '400', sem: '2', type: 'Degree', department: 'DMCD' },
  { name: 'Asante Selina', id: '100009', nationality: 'Ghanaian', programme: 'BTech Digital Media & Communication Des.', level: '400', sem: '2', type: 'Degree', department: 'DMCD' },
  { name: 'Aseda Ewusie Mensah', id: '100144', nationality: 'Ghanaian', programme: 'Certificate in Digital Photography', level: 'Cert.', sem: '1', type: 'Certificate', department: 'DMCD' },
  { name: 'Loyd Asiedu Kissi', id: '100143', nationality: 'Ghanaian', programme: 'Certificate in Digital Photography', level: 'Cert.', sem: '1', type: 'Certificate', department: 'DMCD' },
  { name: 'Mathias Yebalong Kango', id: '100163', nationality: 'Ghanaian', programme: 'Cert. in Digital Media & Comm. Des.', level: 'Cert.', sem: '1', type: 'Certificate', department: 'DMCD' },
  { name: 'Clive Kofi Akoto', id: '100150', nationality: 'Ghanaian', programme: 'Cert. in Digital Media & Comm. Des.', level: 'Cert.', sem: '1', type: 'Certificate', department: 'DMCD' },
  { name: 'Angel Naa Atswei Adjei', id: '100167', nationality: 'Ghanaian', programme: 'Cert. in Digital Media & Comm. Des.', level: 'Cert.', sem: '1', type: 'Certificate', department: 'DMCD' },
  { name: 'Michael Yaw Dunoo', id: '100118', nationality: 'Ghanaian', programme: 'Certificate in Web Design', level: 'Cert.', sem: '2', type: 'Certificate', department: 'DMCD' },
  { name: 'Walcott Nii Armah Sackey', id: '100124', nationality: 'Ghanaian', programme: 'Cert. in Digital Media & Comm. Des.', level: 'Cert.', sem: '2', type: 'Certificate', department: 'DMCD' },
  { name: 'Daniel Sowah', id: '100089', nationality: 'Ghanaian', programme: 'Cert. in Digital Media & Comm. Des.', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'DMCD' },
  { name: 'Adam Mohammed', id: '100104', nationality: 'Ghanaian', programme: 'Certificate in Web Design', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'DMCD' },
  { name: 'George Lionel Benson', id: '100111', nationality: 'Ghanaian', programme: 'Certificate in Web Design', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'DMCD' },
  { name: 'Etornam Kekeli Klu', id: '100095', nationality: 'Ghanaian', programme: 'Certificate in Animation', level: 'Project', sem: 'Proj.', type: 'Certificate', department: 'DMCD' },

  // PDE
  { name: 'Asare Kelvin Adu', id: '100058', nationality: 'Ghanaian', programme: 'BA Product Design & Entrepreneurship', level: '300', sem: '1', type: 'Degree', department: 'PDE' },
  { name: 'Relali Anani-Zikpie', id: '100136', nationality: 'Ghanaian', programme: 'Certificate in Product Design', level: 'Cert.', sem: '2', type: 'Certificate', department: 'PDE' },
  { name: 'Jeremy Nana Sei', id: '100147', nationality: 'Ghanaian', programme: 'Certificate in Product Design', level: 'Cert.', sem: '1', type: 'Certificate', department: 'PDE' },
  { name: 'Akosua Kyeremaa Asamoah', id: '100169', nationality: 'Ghanaian', programme: 'Diploma in Product Design & Entrepreneurship', level: '100', sem: '1', type: 'Diploma', department: 'PDE' },
  { name: 'Hamza Sherrif', id: '100046', nationality: 'Ghanaian', programme: 'BA Product Design & Entrepreneurship', level: '300', sem: '1', type: 'Degree', department: 'PDE' }
];
