-- 002_seed_staff.sql — seed TUC staff into patients as Staff-type (idempotent).
-- Generated from TUC_STAFF_LIST. Only name + code set; other fields filled in later.
USE tuc_sickbay;
INSERT IGNORE INTO patients (patient_code, full_name, patient_type) VALUES
  ('STF001', 'PROF.EMMANUEL AMANKWAH ASANTE', 'Staff'),
  ('STF002', 'DANIEL FRIMPONG TWUM', 'Staff'),
  ('STF003', 'STEPHANIE ACQUAH DJAN', 'Staff'),
  ('STF004', 'DR ANDREW R O ADDO', 'Staff'),
  ('STF005', 'SELETE DELALI KOMLA OFORI', 'Staff'),
  ('STF006', 'BRIGHT AGBOTSE', 'Staff'),
  ('STF007', 'BRIGHT AGBOSU SENANU', 'Staff'),
  ('STF008', 'SAMUEL NII LANTE WELLINGTON', 'Staff'),
  ('STF009', 'ROBERT BUNKANGSANG BUCHAG', 'Staff'),
  ('STF010', 'DORIS BOAKYEWAA', 'Staff'),
  ('STF011', 'AHIABU SELASI', 'Staff'),
  ('STF012', 'ADJACODJOE AARON EYIRAM', 'Staff'),
  ('STF013', 'MANDELA CHRIS FUDUGAH', 'Staff'),
  ('STF014', 'HONU VICTORIA ABRA', 'Staff'),
  ('STF015', 'KWAME BAAH OWUSU PANIN', 'Staff'),
  ('STF016', 'MAVIS DONKOR', 'Staff'),
  ('STF017', 'WILLIAM DAITEY', 'Staff'),
  ('STF018', 'ISAAC NYARKO OFORI', 'Staff'),
  ('STF019', 'nutifafa korsi fiadzomor', 'Staff'),
  ('STF020', 'SABINA ADJOA ODURO', 'Staff'),
  ('STF021', 'KWABENA ASOMANING', 'Staff'),
  ('STF022', 'MICHEAL OBENG', 'Staff'),
  ('STF023', 'THOMAS OWUSU', 'Staff'),
  ('STF024', 'OLAYINKA OMOTOSHO', 'Staff'),
  ('STF025', 'AARON DAGYAWA', 'Staff'),
  ('STF026', 'KWASHIE JOHN KOFI', 'Staff'),
  ('STF027', 'VIDA ADOMAH', 'Staff'),
  ('STF028', 'VERA WIREDU', 'Staff'),
  ('STF029', 'COMFORT AYIAH', 'Staff'),
  ('STF030', 'ABIGAIL NIMO AMOAKO', 'Staff'),
  ('STF031', 'ALICE KOSSAH', 'Staff'),
  ('STF032', 'DOYI MAWUNYA', 'Staff'),
  ('STF033', 'DUGAH BENJAMIN ELORM', 'Staff'),
  ('STF034', 'SHARON AKUA BEGAH', 'Staff'),
  ('STF035', 'EVELYN SIAME', 'Staff'),
  ('STF036', 'AKOTO TAMAKLOR JERRY JOHN', 'Staff'),
  ('STF037', 'MANDOUR CHARLES DOLL', 'Staff'),
  ('STF038', 'DANIEL KESSE ANSAH', 'Staff'),
  ('STF039', 'ROMAIN KOFI AGBOWADAN', 'Staff'),
  ('STF040', 'SAKYI ISAAC', 'Staff'),
  ('STF041', 'EMMANUEL OWUSU', 'Staff'),
  ('STF042', 'KANTIIHA YAKUBU', 'Staff'),
  ('STF043', 'JOSEPHINE YIRENKYI', 'Staff'),
  ('STF044', 'GODSWAY KWESI AMPEH', 'Staff'),
  ('STF045', 'ZAARATU KAFABA NURUDEEN', 'Staff'),
  ('STF046', 'PHANUEL TOTTOH', 'Staff'),
  ('STF047', 'JERIJEES ALHASSAN', 'Staff'),
  ('STF048', 'GYAMFI ETENGEGENG', 'Staff'),
  ('STF049', 'SARAH QUASHIEGAH', 'Staff'),
  ('STF050', 'BERNICE FIO', 'Staff');
