import React, { useState } from 'react';
import jsPDF from 'jspdf';
import { Document, Packer, Paragraph, TextRun, AlignmentType } from 'docx';
import { FileText, FileType, File as FileIcon } from 'lucide-react';
import type { FormData } from '../App.tsx';

// Visual/feature flag. When false, the original single PDF button renders.
const ENABLE_ENHANCED_UI = true;

interface StepProps {
    formData: FormData;
    handleBack: () => void;
    handleReset: () => void;
    addAuditLog: (event: string) => void;
}

const DISCLAIMER =
    'This document was generated by the WillPro utility. It is a template and MUST be reviewed by a qualified solicitor before execution to ensure it is legally binding and meets your specific needs.';

interface Section { title: string; body: string[]; }

const ReviewStep = ({ formData, handleBack, handleReset, addAuditLog }: StepProps) => {
    const [isLoading, setIsLoading] = useState(false);

    // ---- Single source of truth: build the will content once, render to any format ----
    const buildWill = (): { titleName: string; declaration: string; sections: Section[];
                            signatureName: string; witnessText: string } => {
        const {
            testatorName, testatorAddress, executorName, alternateExecutorName,
            jurisdiction, realEstate, gifts, hasMinorChildren, guardianName,
            alternateGuardianName, residuaryBeneficiaryName,
        } = formData;

        const sections: Section[] = [];

        let executorText = `I appoint ${executorName || '[Executor Name]'} as the Executor of this, my Will.`;
        if (alternateExecutorName) executorText += ` If this Executor is unable or unwilling to serve, I appoint ${alternateExecutorName} as my alternate Executor.`;
        sections.push({ title: 'Appointment of Executor', body: [executorText] });

        if (hasMinorChildren && guardianName) {
            let g = `I appoint ${guardianName} as the Guardian of my minor children.`;
            if (alternateGuardianName) g += ` If this Guardian is unable or unwilling to serve, I appoint ${alternateGuardianName} as the alternate Guardian.`;
            sections.push({ title: 'Appointment of Guardian', body: [g] });
        }

        if (realEstate.length > 0) {
            sections.push({
                title: 'Real Estate',
                body: realEstate.map(p => `- I give my property described as "${p.description}" located at ${p.location}.`),
            });
        }

        if (gifts.length > 0) {
            sections.push({
                title: 'Specific Gifts',
                body: gifts.map(g => `- I give to ${g.beneficiary} the following item(s): ${g.item}.`),
            });
        }

        if (residuaryBeneficiaryName) {
            sections.push({
                title: 'Residuary Estate',
                body: [`I give all the rest, residue, and remainder of my estate, both real and personal, to ${residuaryBeneficiaryName}.`],
            });
        }

        sections.push({
            title: 'Governing Law',
            body: [`The validity and interpretation of this Will shall be governed by the laws of ${jurisdiction}.`],
        });

        return {
            titleName: testatorName || '[Testator Name]',
            declaration: `I, ${testatorName}, residing at ${testatorAddress}, being of sound mind and memory, do hereby declare this to be my last Will and Testament, revoking all former wills and codicils made by me.`,
            sections,
            signatureName: testatorName || '[Testator Name]',
            witnessText: 'SIGNED, PUBLISHED, AND DECLARED by the above-named Testator as and for their last Will and Testament, in the presence of us, who at their request, in their presence, and in the presence of each other, have hereunto subscribed our names as witnesses.',
        };
    };

    const fileBase = () =>
        `Last_Will_and_Testament_${(formData.testatorName || 'draft').replace(/\s/g, '_')}`;

    const download = (blob: Blob, ext: string) => {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url; a.download = `${fileBase()}.${ext}`;
        document.body.appendChild(a); a.click(); a.remove();
        URL.revokeObjectURL(url);
    };

    // ---- PDF (original jsPDF rendering, driven by buildWill) ----
    const generatePdf = () => {
        const w = buildWill();
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 15;
        let y = 20;

        doc.setFontSize(18); doc.setFont('times', 'bold');
        doc.text('Last Will and Testament', pageWidth / 2, y, { align: 'center' }); y += 10;
        doc.setFontSize(14); doc.text(`of ${w.titleName}`, pageWidth / 2, y, { align: 'center' }); y += 20;

        doc.setFont('times', 'normal'); doc.setFontSize(12);
        const decl = doc.splitTextToSize(w.declaration, pageWidth - margin * 2);
        doc.text(decl, margin, y); y += decl.length * 7 + 10;

        let n = 1;
        for (const s of w.sections) {
            if (y > 250) { doc.addPage(); y = margin; }
            doc.setFont('times', 'bold'); doc.text(`${n++}. ${s.title}`, margin, y); y += 10;
            doc.setFont('times', 'normal');
            for (const para of s.body) {
                const lines = doc.splitTextToSize(para, pageWidth - margin * 2);
                if (y + lines.length * 7 > pageHeight - 30) { doc.addPage(); y = margin; }
                doc.text(lines, margin, y); y += lines.length * 7 + 4;
            }
            y += 6;
        }

        if (y > pageHeight - 80) { doc.addPage(); y = margin; }
        doc.text('IN WITNESS WHEREOF, I have hereunto set my hand this ______ day of ____________________, 20____.', margin, y); y += 20;
        doc.text('________________________________', margin, y); y += 7;
        doc.text(w.signatureName, margin, y); y += 15;
        const witnessLines = doc.splitTextToSize(w.witnessText, pageWidth - margin * 2);
        if (y + witnessLines.length * 7 + 30 > pageHeight - 30) { doc.addPage(); y = margin; }
        doc.text(witnessLines, margin, y); y += witnessLines.length * 7 + 15;
        doc.text('Witness 1: __________________________', margin, y); y += 10;
        doc.text('Witness 2: __________________________', margin, y);

        const totalPages = doc.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            doc.setPage(i);
            const footerY = pageHeight - 20;
            doc.setLineWidth(0.5); doc.line(margin, footerY - 5, pageWidth - margin, footerY - 5);
            doc.setFontSize(8); doc.setFont('times', 'italic');
            doc.text(doc.splitTextToSize(DISCLAIMER, pageWidth - margin * 2), pageWidth / 2, footerY, { align: 'center' });
        }
        doc.save(`${fileBase()}.pdf`);
        addAuditLog('PDF document generated and downloaded');
    };

    // ---- Plain text ----
    const generateTxt = () => {
        const w = buildWill();
        const lines: string[] = [
            'LAST WILL AND TESTAMENT', `of ${w.titleName}`, '', w.declaration, '',
        ];
        let n = 1;
        for (const s of w.sections) {
            lines.push(`${n++}. ${s.title.toUpperCase()}`);
            s.body.forEach(p => lines.push(p));
            lines.push('');
        }
        lines.push('IN WITNESS WHEREOF, I have hereunto set my hand this ______ day of ____________________, 20____.', '',
            '________________________________', w.signatureName, '', w.witnessText, '',
            'Witness 1: __________________________', 'Witness 2: __________________________', '',
            '----', DISCLAIMER);
        download(new Blob([lines.join('\r\n')], { type: 'text/plain;charset=utf-8' }), 'txt');
        addAuditLog('TXT document generated and downloaded');
    };

    // ---- DOCX (real Word document) ----
    const generateDocx = async () => {
        const w = buildWill();
        const paras: Paragraph[] = [
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: 'Last Will and Testament', bold: true, size: 36 })] }),
            new Paragraph({ alignment: AlignmentType.CENTER, children: [new TextRun({ text: `of ${w.titleName}`, size: 28 })] }),
            new Paragraph({ text: '' }),
            new Paragraph({ children: [new TextRun(w.declaration)] }),
            new Paragraph({ text: '' }),
        ];
        let n = 1;
        for (const s of w.sections) {
            paras.push(new Paragraph({ children: [new TextRun({ text: `${n++}. ${s.title}`, bold: true })] }));
            s.body.forEach(p => paras.push(new Paragraph({ children: [new TextRun(p)] })));
            paras.push(new Paragraph({ text: '' }));
        }
        paras.push(
            new Paragraph({ children: [new TextRun('IN WITNESS WHEREOF, I have hereunto set my hand this ______ day of ____________________, 20____.')] }),
            new Paragraph({ text: '' }),
            new Paragraph({ children: [new TextRun('________________________________')] }),
            new Paragraph({ children: [new TextRun(w.signatureName)] }),
            new Paragraph({ text: '' }),
            new Paragraph({ children: [new TextRun(w.witnessText)] }),
            new Paragraph({ text: '' }),
            new Paragraph({ children: [new TextRun('Witness 1: __________________________')] }),
            new Paragraph({ children: [new TextRun('Witness 2: __________________________')] }),
            new Paragraph({ text: '' }),
            new Paragraph({ children: [new TextRun({ text: DISCLAIMER, italics: true, size: 16 })] }),
        );
        const blob = await Packer.toBlob(new Document({ sections: [{ children: paras }] }));
        download(blob, 'docx');
        addAuditLog('DOCX document generated and downloaded');
    };

    const run = async (fn: () => void | Promise<void>) => {
        setIsLoading(true);
        try { await fn(); } finally { setIsLoading(false); }
    };

    const reviewBody = (
        <>
            <h2 className="step-title">Review &amp; Generate</h2>
            <p className="step-subtitle">Please carefully review all the details below. Once confirmed, you can generate your secure document.</p>

            <div className="review-section">
                <h3>Jurisdiction</h3>
                <div className="review-item"><strong>Governing Law:</strong><span>{formData.jurisdiction}</span></div>
            </div>
            <div className="review-section">
                <h3>Testator Information</h3>
                <div className="review-item"><strong>Full Name:</strong><span>{formData.testatorName || 'N/A'}</span></div>
                <div className="review-item"><strong>Address:</strong><span>{formData.testatorAddress || 'N/A'}</span></div>
                <div className="review-item"><strong>Date of Birth:</strong><span>{formData.testatorDob || 'N/A'}</span></div>
            </div>
            <div className="review-section">
                <h3>Appointments</h3>
                <div className="review-item"><strong>Primary Executor:</strong><span>{formData.executorName || 'N/A'}</span></div>
                <div className="review-item"><strong>Alternate Executor:</strong><span>{formData.alternateExecutorName || 'N/A'}</span></div>
                {formData.hasMinorChildren && (
                    <>
                        <div className="review-item" style={{ marginTop: '8px' }}><strong>Primary Guardian:</strong><span>{formData.guardianName || 'N/A'}</span></div>
                        <div className="review-item"><strong>Alternate Guardian:</strong><span>{formData.alternateGuardianName || 'N/A'}</span></div>
                    </>
                )}
            </div>
            <div className="review-section">
                <h3>Real Estate Assets</h3>
                {formData.realEstate.length === 0 ? <p>No real estate assets listed.</p> :
                    formData.realEstate.map((p, i) => <div className="review-item" key={i}><strong>{p.description}</strong><span>{p.location}</span></div>)}
            </div>
            <div className="review-section">
                <h3>Specific Gifts</h3>
                {formData.gifts.length === 0 ? <p>No specific gifts listed.</p> :
                    formData.gifts.map((g, i) => <div className="review-item" key={i}><strong>{g.beneficiary}:</strong><span>{g.item}</span></div>)}
            </div>
            <div className="review-section">
                <h3>Residuary Estate</h3>
                <div className="review-item"><strong>Beneficiary:</strong><span>{formData.residuaryBeneficiaryName || 'N/A'}</span></div>
            </div>
        </>
    );

    // --- Original single-button path (flag off) ---
    if (!ENABLE_ENHANCED_UI) {
        return (
            <div className="review-step">
                {reviewBody}
                <div className="button-group">
                    <button className="back-btn" onClick={handleBack}>Back</button>
                    <button className="continue-btn" onClick={() => run(generatePdf)} disabled={isLoading}>
                        {isLoading ? 'Generating...' : 'Generate Secure Document'}
                    </button>
                </div>
                <div style={{ marginTop: '24px', textAlign: 'center' }}>
                    <button onClick={handleReset} className="start-over-btn">Start Over</button>
                </div>
            </div>
        );
    }

    // --- Enhanced: explicit format choices (PDF / DOCX / TXT) ---
    return (
        <div className="review-step wp-enhanced">
            {reviewBody}

            <div className="wp-generate-block">
                <div className="wp-generate-label">Generate Secure Document as:</div>
                <div className="wp-format-buttons">
                    <button className="wp-format-btn" onClick={() => run(generatePdf)} disabled={isLoading} aria-label="Download PDF">
                        <FileText size={16} /> PDF
                    </button>
                    <button className="wp-format-btn" onClick={() => run(generateDocx)} disabled={isLoading} aria-label="Download Word DOCX">
                        <FileType size={16} /> DOCX
                    </button>
                    <button className="wp-format-btn" onClick={() => run(generateTxt)} disabled={isLoading} aria-label="Download plain text">
                        <FileIcon size={16} /> TXT
                    </button>
                </div>
                {isLoading && <div className="wp-generate-status">Generating…</div>}
            </div>

            <div className="button-group">
                <button className="back-btn" onClick={handleBack}>Back</button>
            </div>
            <div style={{ marginTop: '24px', textAlign: 'center' }}>
                <button onClick={handleReset} className="start-over-btn">Start Over</button>
            </div>
        </div>
    );
};

export default ReviewStep;
