
import type { Programme, Lecturer, Course, LecturerEvaluation, Recommendation, Ratings } from './types';

export const EVALUATION_CRITERIA_CONFIG = {
  "Lecturer's Delivery & Knowledge": [
    { id: 'knowledgeable', label: 'The Lecturer was knowledgeable in the field of study represented by this course.' },
    { id: 'responsive', label: 'The Lecturer always responded to specific questions confidently and promptly.' },
    { id: 'punctual', label: 'The Lecturer was always regular and punctual in class.' },
    { id: 'communicated_objectives', label: 'Course objectives, content and assessment methods were clearly communicated to students.' },
    { id: 'enthusiastic', label: "The Lecturer's teaching style is enthusiastic and stimulating." },
  ],
  'Course Content & Structure': [
    { id: 'well_organized', label: 'The course content was well organized and structured.' },
  ],
  'Assessment & Feedback': [
    { id: 'fair_assessment', label: 'Assessment methods were fair and appropriate.' },
  ],
};

// Data extracted from Asanska University College of Design and Technology Timetables (2025)
export const programmes: Programme[] = [
    { id: 'dmcd_btech', name: 'B.Tech Digital Media and Communication Design' },
    { id: 'fdt_btech', name: 'B.Tech Fashion Design Technology' },
    { id: 'fdt_cert', name: 'Certificate Fashion Design Technology' },
    { id: 'jdt_ba', name: 'B.A. Jewellery Design Technology' },
    { id: 'jdt_dip', name: 'Diploma Jewellery Design Technology' },
    { id: 'pde_ba', name: 'B.A. Product Design & Entrepreneurship' },
    { id: 'pde_dip', name: 'Diploma Product Design' },
];

export const lecturers: Lecturer[] = [
    { id: 'addo', name: 'Dr. Addo' },
    { id: 'daitey', name: 'Mr. Daitey' },
    { id: 'boateng', name: 'Mr. Boateng' },
    { id: 'agbosu', name: 'Mr. Agbosu' },
    { id: 'ahiabu', name: 'Mr. Ahiabu' },
    { id: 'wellington', name: 'Mr. Wellington' },
    { id: 'buchag', name: 'Mr. Buchag' },
    { id: 'kushitor', name: 'Ms. Kushitor' },
    { id: 'oduro', name: 'Ms. Oduro' },
    { id: 'nutifafa', name: 'Mr. Nutifafa' },
    { id: 'takyi', name: 'Ms. Takyi' },
    { id: 'honu', name: 'Ms. Honu' },
    { id: 'adjacodjoe', name: 'Mr. Adjacodjoe' },
    { id: 'ntim_pipim', name: 'Mr. Ntim Pipim' },
    { id: 'morrison', name: 'Mr. Morrison' },
    { id: 'ofori', name: 'Mr. Ofori' },
    { id: 'sackey', name: 'Dr. Sackey' },
    { id: 'tattah', name: 'Mr. Tattah' },
    { id: 'amevor', name: 'Mr. Amevor' },
    { id: 'vivian_yeboah', name: 'Ms. Vivian Yeboah' },
    { id: 'owusu', name: 'Mr. Owusu' },
    { id: 'mills', name: 'Mrs. Elsie Mills' },
    { id: 'boakyewaa', name: 'Ms. Doris Boakyewaa' },
];

const courseData = [
    // B.TECH DIGITAL MEDIA AND COMMUNICATION DESIGN
    { id: 'aucdt_115', name: 'AUCDT 115 - Intro to African Art & Culture', p: 'dmcd_btech', l: ['addo'] },
    { id: 'aucdt_116', name: 'AUCDT 116 - Intro to Communication Skills', p: 'dmcd_btech', l: ['boateng'] },
    { id: 'dmcd_112', name: 'DMCD 112 - Basic Design', p: 'dmcd_btech', l: ['daitey'] },
    { id: 'aucdt_114', name: 'AUCDT 114 - Basic Drawing', p: 'dmcd_btech', l: ['daitey'] },
    { id: 'aucdt_117', name: 'AUCDT 117 - Intro to Info & Comm Tech', p: 'dmcd_btech', l: ['agbosu'] },
    { id: 'dmcd_113', name: 'DMCD 113 - Intro to Communication Design', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_111', name: 'DMCD 111 - Intro to Digital Media', p: 'dmcd_btech', l: ['wellington'] },
    { id: 'dmcd_114_graph', name: 'DMCD 114 - Intro to Comp Graphics Apps', p: 'dmcd_btech', l: ['buchag'] },
    { id: 'dmcd_122', name: 'DMCD 122 - Idea Development Techniques', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_121', name: 'DMCD 121 - Basic Programming', p: 'dmcd_btech', l: ['wellington'] },
    { id: 'dmcd_125', name: 'DMCD 125 - Intro to Typography', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_126', name: 'DMCD 126 - Image Manipulation', p: 'dmcd_btech', l: ['buchag'] },
    { id: 'dmcd_123', name: 'DMCD 123 - Basic Rendering Techniques', p: 'dmcd_btech', l: ['wellington'] },
    { id: 'dmcd_124', name: 'DMCD 124 - Design History', p: 'dmcd_btech', l: ['wellington'] },
    { id: 'aucdt_126', name: 'AUCDT 126 - Communication Skills', p: 'dmcd_btech', l: ['boateng'] },
    { id: 'aucdt_127', name: 'AUCDT 127 - Info & Comm Tech', p: 'dmcd_btech', l: ['agbosu'] },
    { id: 'dmcd_236', name: 'DMCD 236 - Intro to Animation', p: 'dmcd_btech', l: ['wellington'] },
    { id: 'dmcd_231', name: 'DMCD 231 - Corporate Identity', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_232', name: 'DMCD 232 - Print Design', p: 'dmcd_btech', l: ['buchag'] },
    { id: 'dmcd_233', name: 'DMCD 233 - Typography & Basic Layout', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_235', name: 'DMCD 235 - Print Production', p: 'dmcd_btech', l: ['buchag'] },
    { id: 'dmcd_234', name: 'DMCD 234 - Fundamentals of Photography', p: 'dmcd_btech', l: ['wellington'] },
    { id: 'dmcd_237', name: 'DMCD 237 - Intro to Production Mgmt', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_242', name: 'DMCD 242 - Digital Print Technology', p: 'dmcd_btech', l: ['buchag'] },
    { id: 'dmcd_244', name: 'DMCD 244 - Digital Photography', p: 'dmcd_btech', l: ['wellington'] },
    { id: 'dmcd_241', name: 'DMCD 241 - Brand and Identity Systems', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_245', name: 'DMCD 245 - Digital Print Production', p: 'dmcd_btech', l: ['buchag'] },
    { id: 'dmcd_246', name: 'DMCD 246 - Video Production & Motion', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_243', name: 'DMCD 243 - Web Design', p: 'dmcd_btech', l: ['agbosu'] },
    { id: 'dmcd_353', name: 'DMCD 353 - Online Media Technology', p: 'dmcd_btech', l: ['agbosu'] },
    { id: 'dmcd_352', name: 'DMCD 352 - Advertising Design', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_351', name: 'DMCD 351 - Book & Magazine Design', p: 'dmcd_btech', l: ['buchag'] },
    { id: 'dmcd_354', name: 'DMCD 354 - Animation', p: 'dmcd_btech', l: ['wellington'] },
    { id: 'dmcd_355', name: 'DMCD 355 - Copywriting', p: 'dmcd_btech', l: ['agbosu'] },
    { id: 'dmcd_357', name: 'DMCD 357 - Motion Graphics', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'dmcd_356', name: 'DMCD 356 - Video Production', p: 'dmcd_btech', l: ['ofori'] },
    { id: 'aucdt_352', name: 'AUCDT 352 - Seminar in DMCD', p: 'dmcd_btech', l: ['addo'] },
    { id: 'aucdt_351', name: 'AUCDT 351 - Intro to Entrepreneurship', p: 'dmcd_btech', l: ['ntim_pipim'] },
    { id: 'acdt_352', name: 'ACDT 352 - Research Methods', p: 'dmcd_btech', l: ['addo'] },
    { id: 'acdt_351', name: 'ACDT 351 - Industrial Attachment', p: 'dmcd_btech', l: [] },
    { id: 'dmcd_471', name: 'DMCD 471 - Sound Production', p: 'dmcd_btech', l: ['ofori'] },
    { id: 'dmcd_352_anim', name: 'DMCD 352 - Interactive Animation', p: 'dmcd_btech', l: ['ofori'] },
    { id: 'dmcd_472', name: 'DMCD 472 - Portfolio Development', p: 'dmcd_btech', l: ['agbosu'] },
    { id: 'dmcd_473', name: 'DMCD 473 - Video Post Production', p: 'dmcd_btech', l: ['ofori'] },
    { id: 'dmcd_475', name: 'DMCD 475 - Advertising Design Technology', p: 'dmcd_btech', l: ['ahiabu'] },
    { id: 'aucdt_472', name: 'AUCDT 472 - Thesis / Project', p: 'dmcd_btech', l: ['buchag'] },
    { id: 'aucdt_471', name: 'AUCDT 471 - Entrepreneurship', p: 'dmcd_btech', l: ['ntim_pipim'] },
    // B.TECH FASHION DESIGN TECHNOLOGY
    { id: 'acdt_115_fdt', name: 'ACDT 115 - Intro to African Art & Culture', p: 'fdt_btech', l: ['addo'] },
    { id: 'acdt_116_fdt', name: 'ACDT 116 - Communication Skills I', p: 'fdt_btech', l: ['boateng'] },
    { id: 'fdt_114', name: 'FDT 114 - Sewing Techniques', p: 'fdt_btech', l: ['kushitor'] },
    { id: 'acdt_114_fdt', name: 'ACDT 114 - Basic Drawing', p: 'fdt_btech', l: ['daitey'] },
    { id: 'fdt_111', name: 'FDT 111 - Introduction to Fashion', p: 'fdt_btech', l: ['oduro'] },
    { id: 'acdt_117_fdt', name: 'ACDT 117 - Info & Comm Tech I', p: 'fdt_btech', l: ['agbosu'] },
    { id: 'fdt_113', name: 'FDT 113 - Basic Pattern Technology', p: 'fdt_btech', l: ['takyi'] },
    { id: 'fdt_112', name: 'FDT 112 - Introduction to Textiles', p: 'fdt_btech', l: ['nutifafa'] },
    { id: 'fdt_122', name: 'FDT 122 - Textile Design', p: 'fdt_btech', l: ['nutifafa'] },
    { id: 'fdt_123', name: 'FDT 123 - Pattern Adaptation', p: 'fdt_btech', l: ['oduro'] },
    { id: 'fdt_124', name: 'FDT 124 - Garment Construction', p: 'fdt_btech', l: ['oduro'] },
    { id: 'acdt_126_fdt', name: 'ACDT 126 - Communication Skills II', p: 'fdt_btech', l: ['boateng'] },
    { id: 'fdt_125', name: 'FDT 125 - Freehand Cutting', p: 'fdt_btech', l: ['honu'] },
    { id: 'fdt_126_fdt', name: 'FDT 126 - Basic Design', p: 'fdt_btech', l: ['takyi'] },
    { id: 'acdt_127_fdt', name: 'ACDT 127 - Info & Comm Tech II', p: 'fdt_btech', l: ['agbosu'] },
    { id: 'fdt_121_fdt', name: 'FDT 121 - Intro to Creative Design in Fashion', p: 'fdt_btech', l: ['honu'] },
    { id: 'fdt_237_fdt', name: 'FDT 237 - Basic Computer Aided Design', p: 'fdt_btech', l: ['adjacodjoe'] },
    { id: 'fdt_235_fdt', name: 'FDT 235 - Introduction to Fabric Studies', p: 'fdt_btech', l: ['oduro'] },
    { id: 'fdt_234', name: 'FDT 234 - Garment Technology I', p: 'fdt_btech', l: ['oduro'] },
    { id: 'fdt_232_fdt', name: 'FDT 232 - Printed Textile Design Application', p: 'fdt_btech', l: ['nutifafa'] },
    { id: 'fdt_231_fdt', name: 'FDT 231 - Creative Design in Fashion', p: 'fdt_btech', l: ['takyi'] },
    { id: 'fdt_233_fdt', name: 'FDT 233 - Pattern Technology I', p: 'fdt_btech', l: ['oduro'] },
    { id: 'fdt_239', name: 'FDT 239 - Intro to Production Management', p: 'fdt_btech', l: ['ntim_pipim'] },
    { id: 'fdt_238', name: 'FDT 238 - Introduction to Fashion Accessories', p: 'fdt_btech', l: ['takyi'] },
    { id: 'fdt_236_fdt', name: 'FDT 236 - Fashion Illustration', p: 'fdt_btech', l: ['nutifafa'] },
    { id: 'fdt_241_fdt', name: 'FDT 241 - Basic Fashion Design and Illustration', p: 'fdt_btech', l: ['takyi'] },
    { id: 'fdt_245', name: 'FDT 245 - Millinery Design and Production', p: 'fdt_btech', l: ['takyi'] },
    { id: 'fdt_244', name: 'FDT 244 - Fabric Studies', p: 'fdt_btech', l: ['nutifafa'] },
    { id: 'fdt_246', name: 'FDT 246 - Computer-Aided Design', p: 'fdt_btech', l: ['adjacodjoe'] },
    { id: 'fdt_242', name: 'FDT 242 - Pattern Technology II', p: 'fdt_btech', l: ['morrison'] },
    { id: 'fdt_243', name: 'FDT 243 - Garment Technology II', p: 'fdt_btech', l: ['morrison'] },
    { id: 'fdt_248', name: 'FDT 248 - Production Management', p: 'fdt_btech', l: ['ntim_pipim'] },
    { id: 'fdt_247_fdt', name: 'FDT 247 - Fashion Marketing', p: 'fdt_btech', l: ['ntim_pipim'] },
    { id: 'fdt_352', name: 'FDT 352 - Garment Decoration Techniques', p: 'fdt_btech', l: ['honu'] },
    { id: 'fdt_351_fdt', name: 'FDT 351 - Design and Illustration', p: 'fdt_btech', l: ['nutifafa'] },
    { id: 'fdt_355', name: 'FDT 355 - Design & Production of Bags & Slippers', p: 'fdt_btech', l: ['takyi'] },
    { id: 'fdt_354', name: 'FDT 354 - Fashion Draping', p: 'fdt_btech', l: ['kushitor'] },
    { id: 'fdt_353_fdt', name: 'FDT 353 - Pattern Alteration', p: 'fdt_btech', l: ['oduro'] },
    { id: 'fdt_357', name: 'FDT 357 - Seminar in Fashion', p: 'fdt_btech', l: ['addo'] },
    { id: 'fdt_356', name: 'FDT 356 - Entrepreneurship I', p: 'fdt_btech', l: ['ntim_pipim'] },
    { id: 'acdt_352_fdt', name: 'ACDT 352 - Research Methods', p: 'fdt_btech', l: ['addo'] },
    { id: 'acdt_351_fdt', name: 'ACDT 351 - Industrial Attachment', p: 'fdt_btech', l: [] },
    { id: 'fdt_471', name: 'FDT 471 - Collection Development', p: 'fdt_btech', l: ['honu'] },
    { id: 'fdt_473', name: 'FDT 473 - Beauty Culture', p: 'fdt_btech', l: ['takyi'] },
    // CERTIFICATE FASHION DESIGN TECHNOLOGY
    { id: 'cfdt_235', name: 'CFDT 235 - Intro to Fabric Studies', p: 'fdt_cert', l: ['nutifafa'] },
    { id: 'cfdt_114', name: 'CFDT 114 - Garment Construction', p: 'fdt_cert', l: ['vivian_yeboah'] },
    { id: 'cfdt_247', name: 'CFDT 247 - Fashion Marketing', p: 'fdt_cert', l: ['ntim_pipim'] },
    { id: 'cfdt_113', name: 'CFDT 113 - Basic Pattern Technology', p: 'fdt_cert', l: ['vivian_yeboah'] },
    { id: 'cfdt_236', name: 'CFDT 236 - Fashion Illustration', p: 'fdt_cert', l: ['nutifafa'] },
    { id: 'cfdt_233', name: 'CFDT 233 - Pattern Technology I', p: 'fdt_cert', l: ['vivian_yeboah'] },
    { id: 'cfdt_234', name: 'CFDT 234 - Garment Technology I', p: 'fdt_cert', l: ['vivian_yeboah'] },
    // B.A. JEWELLERY DESIGN TECHNOLOGY
    { id: 'acdt_115_jdt', name: 'ACDT 115 - Intro to African Art & Culture', p: 'jdt_ba', l: ['addo'] },
    { id: 'acdt_116_jdt', name: 'ACDT 116 - Communication Skills I', p: 'jdt_ba', l: ['boateng'] },
    { id: 'acdt_113_jdt', name: 'ACDT 113 - Foundations in Technical Drawing', p: 'jdt_ba', l: ['amevor'] },
    { id: 'acdt_114_jdt', name: 'ACDT 114 - Basic Drawing', p: 'jdt_ba', l: ['daitey'] },
    { id: 'bjdt_111', name: 'BJDT 111 - Intro to Jewellery Design', p: 'jdt_ba', l: ['addo'] },
    { id: 'acdt_117_jdt', name: 'ACDT 117 - Info & Comm Tech I', p: 'jdt_ba', l: ['agbosu'] },
    { id: 'acdt_112_jdt', name: 'ACDT 112 - Workshop Safety Practices', p: 'jdt_ba', l: ['ofori'] },
    { id: 'acdt_231_jdt', name: 'ACDT 231 - Intro to Entrepreneurship', p: 'jdt_ba', l: ['ntim_pipim'] },
    { id: 'bjdt_232', name: 'BJDT 232 - Basic Fabrication and Finishing', p: 'jdt_ba', l: ['ofori'] },
    { id: 'bjdt_236', name: 'BJDT 236 - 3D Modelling in Computer', p: 'jdt_ba', l: ['adjacodjoe'] },
    { id: 'bjdt_233', name: 'BJDT 233 - Alloy Calculation, Measuring and Marking', p: 'jdt_ba', l: ['owusu'] },
    { id: 'bjdt_234', name: 'BJDT 234 - Intro to Metallurgy', p: 'jdt_ba', l: ['owusu'] },
    { id: 'bjdt_231_concept', name: 'BJDT 231 - Concept Design and Modelling', p: 'jdt_ba', l: ['ofori'] },
    { id: 'bjdt_235', name: 'BJDT 235 - Refining, Assaying & Hallmarking', p: 'jdt_ba', l: ['addo'] },
    { id: 'bjdt_245', name: 'BJDT 245 - Metallurgy', p: 'jdt_ba', l: ['owusu'] },
    { id: 'bjdt_241', name: 'BJDT 241 - Practical Design and Modelling Processes', p: 'jdt_ba', l: ['ofori'] },
    { id: 'bjdt_246', name: 'BJDT 246 - Advanced Computer Application', p: 'jdt_ba', l: ['adjacodjoe'] },
    { id: 'bjdt_244', name: 'BJDT 244 - Jewellery Surface Coating Methods', p: 'jdt_ba', l: ['ofori'] },
    { id: 'bjdt_242', name: 'BJDT 242 - Fabrication and Finishing Techniques', p: 'jdt_ba', l: ['ofori'] },
    { id: 'bjdt_243', name: 'BJDT 243 - Jewellery Casting Methods', p: 'jdt_ba', l: ['owusu'] },
    { id: 'acdt_247_jdt', name: 'ACDT 247 - Developing a New Venture', p: 'jdt_ba', l: ['ntim_pipim'] },
    { id: 'bjdt_352_jdt', name: 'BJDT 352 - Fabrication and Finishing Practices', p: 'jdt_ba', l: ['ofori'] },
    { id: 'bjdt_353', name: 'BJDT 353 - Intro to Gemmology', p: 'jdt_ba', l: ['owusu'] },
    { id: 'bjdt_354', name: 'BJDT 354 - Intro to Gem Setting', p: 'jdt_ba', l: ['addo'] },
    { id: 'bjdt_351', name: 'BJDT 351 - Advanced Designs and Modelling Techniques', p: 'jdt_ba', l: ['owusu'] },
    { id: 'acdt_356_jdt', name: 'ACDT 356 - Business Management and Sustainability', p: 'jdt_ba', l: ['ntim_pipim'] },
    { id: 'bjdt_355', name: 'BJDT 355 - Seminar in Jewellery', p: 'jdt_ba', l: ['addo', 'ofori', 'owusu'] },
    { id: 'acdt_352_jdt', name: 'ACDT 352 - Research Methods', p: 'jdt_ba', l: ['addo'] },
    { id: 'acdt_351_jdt', name: 'ACDT 351 - Industrial Attachment', p: 'jdt_ba', l: [] },
    // DIPLOMA JEWELLERY DESIGN TECHNOLOGY
    { id: 'acdt_115_jdt_dip', name: 'ACDT 115 - Intro to African Art & Culture', p: 'jdt_dip', l: ['addo'] },
    { id: 'acdt_116_jdt_dip', name: 'ACDT 116 - Communication Skills I', p: 'jdt_dip', l: ['boateng'] },
    { id: 'acdt_113_jdt_dip', name: 'ACDT 113 - Foundations in Technical Drawing', p: 'jdt_dip', l: ['amevor'] },
    { id: 'acdt_114_jdt_dip', name: 'ACDT 114 - Basic Drawing', p: 'jdt_dip', l: ['daitey'] },
    { id: 'bjdt_111_dip', name: 'BJDT 111 - Intro to Jewellery Design', p: 'jdt_dip', l: ['addo'] },
    { id: 'acdt_117_jdt_dip', name: 'ACDT 117 - Info & Comm Tech I', p: 'jdt_dip', l: ['agbosu'] },
    { id: 'acdt_112_dip', name: 'ACDT 112 - Workshop Safety Practices', p: 'jdt_dip', l: ['ofori'] },
    { id: 'djdt_231', name: 'DJDT 231 - Fabrication and Finishing Practices', p: 'jdt_dip', l: ['ofori'] },
    { id: 'acdt_236_jdt_dip', name: 'ACDT 236 - Advanced Computer Application in Jewellery', p: 'jdt_dip', l: ['adjacodjoe'] },
    { id: 'djdt_232', name: 'DJDT 232 - Alloy Calculation, Measuring and Marking', p: 'jdt_dip', l: ['owusu'] },
    { id: 'djdt_233', name: 'DJDT 233 - Intro to Metallurgy', p: 'jdt_dip', l: ['owusu'] },
    { id: 'acdt_237_jdt_dip', name: 'ACDT 237 - Research Methodology', p: 'jdt_dip', l: ['sackey'] },
    // B.A. PRODUCT DESIGN & ENTREPRENEURSHIP
    { id: 'acdt_115_pde', name: 'ACDT 115 - Intro to African Art & Culture', p: 'pde_ba', l: ['addo'] },
    { id: 'acdt_116_pde', name: 'ACDT 116 - Communication Skills I', p: 'pde_ba', l: ['boateng'] },
    { id: 'acdt_113_pde', name: 'ACDT 113 - Technical Drawing', p: 'pde_ba', l: ['amevor'] },
    { id: 'acdt_114_pde', name: 'ACDT 114 - Basic Drawing', p: 'pde_ba', l: ['daitey'] },
    { id: 'bpde_111', name: 'BPDE 111 - Intro to Industrial/Product Design', p: 'pde_ba', l: ['adjacodjoe'] },
    { id: 'acdt_117_pde', name: 'ACDT 117 - Info & Comm Tech I', p: 'pde_ba', l: ['agbosu'] },
    { id: 'acdt_112_pde', name: 'ACDT 112 - Safety in Workshop Practices', p: 'pde_ba', l: ['ofori'] },
    { id: 'acdt_125_pde', name: 'ACDT 125 - Intro to Computer-Aided-Design', p: 'pde_ba', l: ['daitey'] },
    { id: 'bpde_122', name: 'BPDE 122 - Workshop Practices', p: 'pde_ba', l: ['tattah'] },
    { id: 'bpde_123', name: 'BPDE 123 - Orthographic and Isometric Projections', p: 'pde_ba', l: ['amevor'] },
    { id: 'acdt_126_pde', name: 'ACDT 126 - Communication Skills II', p: 'pde_ba', l: ['boateng'] },
    { id: 'bpde_124', name: 'BPDE 124 - Freehand Drawing Techniques', p: 'pde_ba', l: ['daitey'] },
    { id: 'bpde_121', name: 'BPDE 121 - Idea Development and Design Processes', p: 'pde_ba', l: ['adjacodjoe'] },
    { id: 'acdt_127_pde', name: 'ACDT 127 - Info & Comm Tech II', p: 'pde_ba', l: ['agbosu'] },
    { id: 'bpde_235_pde', name: 'BPDE 235 - Manufacturing Processes 1', p: 'pde_ba', l: ['tattah'] },
    { id: 'bpde_231_pde', name: 'BPDE 231 - Intro to Modelling', p: 'pde_ba', l: ['adjacodjoe'] },
    { id: 'bpde_236_pde', name: 'BPDE 236 - Three-Dimensional in Computing', p: 'pde_ba', l: ['daitey'] },
    { id: 'bpde_234', name: 'BPDE 234 - Nature of Materials & Processes', p: 'pde_ba', l: ['tattah'] },
    { id: 'bpde_233_pde', name: 'BPDE 233 - Perspective Drawing', p: 'pde_ba', l: ['daitey'] },
    { id: 'acdt_231_pde', name: 'ACDT 231 - Intro to Entrepreneurship', p: 'pde_ba', l: ['ntim_pipim'] },
    { id: 'bpde_232_pde', name: 'BPDE 232 - Product Design Methods', p: 'pde_ba', l: ['adjacodjoe'] },
    { id: 'bpde_241_pde', name: 'BPDE 241 - Design for Use', p: 'pde_ba', l: ['daitey'] },
    { id: 'bpde_245_pde', name: 'BPDE 245 - Objects and Impacts', p: 'pde_ba', l: ['daitey'] },
    { id: 'bpde_246_pde', name: 'BPDE 246 - Advanced Computer Application', p: 'pde_ba', l: ['adjacodjoe'] },
    { id: 'bpde_242', name: 'BPDE 242 - Visual Communication and Package Design', p: 'pde_ba', l: ['ahiabu'] },
    { id: 'bpde_244_pde', name: 'BPDE 244 - Contextual Nature of Products', p: 'pde_ba', l: ['adjacodjoe'] },
    { id: 'bpde_243_pde', name: 'BPDE 243 - Ergonomics and Human Factors Applications', p: 'pde_ba', l: ['daitey'] },
    { id: 'bpde_247_pde', name: 'BPDE 247 - New Venture Creation', p: 'pde_ba', l: ['ntim_pipim'] },
    { id: 'bpde_354_pde', name: 'BPDE 354 - Design and Development', p: 'pde_ba', l: ['adjacodjoe'] },
    { id: 'bpde_351_pde', name: 'BPDE 351 - Practical Model Making Techniques', p: 'pde_ba', l: ['tattah'] },
    { id: 'bpde_352_pde', name: 'BPDE 352 - Product Interface Design', p: 'pde_ba', l: ['daitey'] },
    { id: 'acdt_356_pde', name: 'ACDT 356 - Business Management and Sustainability', p: 'pde_ba', l: ['ntim_pipim'] },
    { id: 'bpde_353_pde', name: 'BPDE 353 - Workshop Practice I', p: 'pde_ba', l: ['tattah'] },
    // DIPLOMA PRODUCT DESIGN
    { id: 'acdt_115_pde_dip', name: 'ACDT 115 - Intro to African Art & Culture', p: 'pde_dip', l: ['addo'] },
    { id: 'acdt_116_pde_dip', name: 'ACDT 116 - Communication Skills I', p: 'pde_dip', l: ['boateng'] },
    { id: 'dpd_113', name: 'DPD 113 - Foundations in Technical Drawing', p: 'pde_dip', l: ['amevor'] },
    { id: 'dpd_114', name: 'DPD 114 - Idea Development and Design Processes', p: 'pde_dip', l: ['adjacodjoe'] },
    { id: 'dpd_111', name: 'DPD 111 - Intro to Industrial/Product Design', p: 'pde_dip', l: ['adjacodjoe'] },
    { id: 'acdt_117_pde_dip', name: 'ACDT 117 - Info & Comm Tech I', p: 'pde_dip', l: ['agbosu'] },
    { id: 'acdt_112_pde_dip', name: 'ACDT 112 - Safety in Workshop Practices', p: 'pde_dip', l: ['ofori'] },
];

const uniqueCourses = new Map<string, Course>();
courseData.forEach(course => {
    // A course can be taught in multiple programmes, but the ID should be unique for the dataset
    const uniqueId = `${course.p}-${course.id}`;
    if (!uniqueCourses.has(uniqueId)) {
        uniqueCourses.set(uniqueId, {
            id: course.id,
            name: course.name,
            programmeId: course.p,
            lecturerIds: course.l,
        });
    }
});
export const courses: Course[] = Array.from(uniqueCourses.values());

/**
 * Helper function to generate plausible sample evaluation data.
 */
const createSampleEvaluation = (
    id: string,
    programmeId: string,
    lecturerId: string,
    courseId: string,
    semester: number,
    recommend: Recommendation,
    comment: string,
    baseRating: number
): LecturerEvaluation => {
    const ratings: Ratings = {};
    Object.values(EVALUATION_CRITERIA_CONFIG).flat().forEach(criterion => {
        const variation = Math.floor(Math.random() * 3) - 1; // -1, 0, or 1
        let rating = baseRating + variation;
        if (rating > 5) rating = 5;
        if (rating < 1) rating = 1;
        ratings[criterion.id] = rating;
    });
    return {
        id: `eval_${id}`,
        programmeId,
        lecturerId,
        courseId,
        semester,
        ratings,
        recommend,
        comment,
        timestamp: new Date(`2024-05-${id.padStart(2, '0')}`).toISOString(),
    };
};

export const sampleEvaluations: LecturerEvaluation[] = [
    createSampleEvaluation('1', 'dmcd_btech', 'ahiabu', 'dmcd_113', 1, 'Recommend', "Mr. Ahiabu is a fantastic lecturer. He explains complex topics in a simple way.", 5),
    createSampleEvaluation('2', 'dmcd_btech', 'wellington', 'dmcd_111', 1, 'Recommend', "", 4),
    createSampleEvaluation('3', 'fdt_btech', 'kushitor', 'fdt_114', 2, 'Recommend', "Ms. Kushitor is very knowledgeable and always willing to help students.", 5),
    createSampleEvaluation('4', 'fdt_btech', 'oduro', 'fdt_111', 2, 'Neutral', "The course was okay, but the assignments were not very engaging.", 3),
    createSampleEvaluation('5', 'jdt_ba', 'addo', 'bjdt_111', 3, 'Not Recommend', "Dr. Addo was often late to class and seemed unprepared. It was hard to follow the lectures.", 2),
    createSampleEvaluation('6', 'pde_ba', 'adjacodjoe', 'bpde_111', 4, 'Recommend', "Loved this course! Mr. Adjacodjoe made it very interesting and practical.", 5),
    createSampleEvaluation('7', 'dmcd_btech', 'ahiabu', 'dmcd_231', 3, 'Recommend', "Another great course with Mr. Ahiabu. The projects were challenging but rewarding.", 5),
    createSampleEvaluation('8', 'fdt_btech', 'nutifafa', 'fdt_112', 1, 'Recommend', "The practical sessions for textile design were excellent.", 4),
];
