import { Trait } from './types';

export const PREDEFINED_TRAITS: Trait[] = [
  { id: 'creative', label: 'Creative', emoji: '🎨' },
  { id: 'analytical', label: 'Analytical', emoji: '🔬' },
  { id: 'empathetic', label: 'Empathetic', emoji: '💛' },
  { id: 'ambitious', label: 'Ambitious', emoji: '🚀' },
  { id: 'adventurous', label: 'Adventurous', emoji: '🧭' },
  { id: 'organized', label: 'Organized', emoji: '📋' },
  { id: 'curious', label: 'Curious', emoji: '🔍' },
  { id: 'loyal', label: 'Loyal', emoji: '🛡️' },
  { id: 'visionary', label: 'Visionary', emoji: '🌅' },
  { id: 'humorous', label: 'Humorous', emoji: '😄' },
  { id: 'strategic', label: 'Strategic', emoji: '♟️' },
  { id: 'nurturing', label: 'Nurturing', emoji: '🌿' },
  { id: 'independent', label: 'Independent', emoji: '🦅' },
  { id: 'disciplined', label: 'Disciplined', emoji: '⚖️' },
  { id: 'passionate', label: 'Passionate', emoji: '🔥' },
  { id: 'resilient', label: 'Resilient', emoji: '💪' },
  { id: 'intuitive', label: 'Intuitive', emoji: '✨' },
  { id: 'collaborative', label: 'Collaborative', emoji: '🤝' },
  { id: 'authentic', label: 'Authentic', emoji: '🪞' },
  { id: 'patient', label: 'Patient', emoji: '🕊️' },
  { id: 'bold', label: 'Bold', emoji: '⚡' },
  { id: 'thoughtful', label: 'Thoughtful', emoji: '📚' },
  { id: 'optimistic', label: 'Optimistic', emoji: '🌈' },
  { id: 'competitive', label: 'Competitive', emoji: '🏆' },
  { id: 'compassionate', label: 'Compassionate', emoji: '❤️' },
  { id: 'innovative', label: 'Innovative', emoji: '💡' },
  { id: 'grounded', label: 'Grounded', emoji: '🌍' },
  { id: 'expressive', label: 'Expressive', emoji: '🎭' },
  { id: 'methodical', label: 'Methodical', emoji: '🗂️' },
  { id: 'charismatic', label: 'Charismatic', emoji: '🌟' },
  { id: 'protective', label: 'Protective', emoji: '🧱' },
  { id: 'spiritual', label: 'Spiritual', emoji: '🕯️' },
  { id: 'pragmatic', label: 'Pragmatic', emoji: '🔧' },
  { id: 'idealistic', label: 'Idealistic', emoji: '🌠' },
  { id: 'determined', label: 'Determined', emoji: '🎯' },
  { id: 'reflective', label: 'Reflective', emoji: '🪷' },
  { id: 'leader', label: 'Leader', emoji: '👑' },
  { id: 'peacemaker', label: 'Peacemaker', emoji: '☮️' },
  { id: 'maverick', label: 'Maverick', emoji: '🃏' },
  { id: 'stoic', label: 'Stoic', emoji: '🗿' },
];
