import { Contact, RoleCategory, SchoolLevel } from './types';

export const APP_NAME = "VECA";
export const APP_VERSION = "1.0";
export const LAST_UPDATED = "25 November 2025";

// Mock Data for Phase 1 Visualization
export const MOCK_CONTACTS: Contact[] = [
  {
    contact_id: 101,
    first_name: "Sarah",
    last_name: "Miller",
    job_title_raw: "Director of Curriculum & Instruction",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "smiller@cvsdvt.org",
    phone_main: "(802) 383-1234",
    district_name: "Champlain Valley SD",
    county: "Chittenden",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-20T10:00:00Z"
  },
  {
    contact_id: 102,
    first_name: "James",
    last_name: "Whitmore",
    job_title_raw: "Executive Director of Learning",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "jwhitmore@bsdvt.org",
    phone_main: "(802) 865-5332",
    district_name: "Burlington SD",
    county: "Chittenden",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-21T09:00:00Z"
  },
  {
    contact_id: 103,
    first_name: "Elena",
    last_name: "Ricci",
    job_title_raw: "Asst. Superintendent",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "ericci@svsu.org",
    phone_main: "(802) 447-7501",
    district_name: "Southwest Vermont SU",
    county: "Bennington",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-15T09:15:00Z"
  },
  {
    contact_id: 104,
    first_name: "Michael",
    last_name: "O'Malley",
    job_title_raw: "Director of Instruction",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "momalley@ewsd.org",
    phone_main: "(802) 878-8168",
    district_name: "Essex Westford SD",
    county: "Chittenden",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-22T11:45:00Z"
  },
  {
    contact_id: 105,
    first_name: "Rebecca",
    last_name: "Holt",
    job_title_raw: "Director of Curriculum",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "rholt@sbschools.net",
    phone_main: "(802) 652-7250",
    district_name: "South Burlington SD",
    county: "Chittenden",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-23T14:20:00Z"
  },
  {
    contact_id: 106,
    first_name: "Thomas",
    last_name: "Warner",
    job_title_raw: "Director of Learning",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "twarner@wsdvt.org",
    phone_main: "(802) 655-0485",
    district_name: "Winooski SD",
    county: "Chittenden",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-20T13:10:00Z"
  },
  {
    contact_id: 107,
    first_name: "Linda",
    last_name: "Carson",
    job_title_raw: "Curriculum Coordinator",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "lcarson@mtsd-vt.org",
    phone_main: "(802) 893-5400",
    district_name: "Milton Town SD",
    county: "Chittenden",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-19T10:30:00Z"
  },
  {
    contact_id: 108,
    first_name: "Robert",
    last_name: "Frost",
    job_title_raw: "Director of Curriculum, Instruction & Assessment",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "rfrost@mrpsvt.org",
    phone_main: "(802) 223-9796",
    district_name: "Montpelier Roxbury SD",
    county: "Washington",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-24T08:50:00Z"
  },
  {
    contact_id: 109,
    first_name: "Jennifer",
    last_name: "Stark",
    job_title_raw: "Asst. Supt. of Instruction",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "jstark@buusd.org",
    phone_main: "(802) 476-5011",
    district_name: "Barre UUSD",
    county: "Washington",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-21T15:00:00Z"
  },
  {
    contact_id: 110,
    first_name: "Patricia",
    last_name: "Doyle",
    job_title_raw: "Director of Curriculum",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "pdoyle@huusd.org",
    phone_main: "(802) 496-2272",
    district_name: "Harwood UUSD",
    county: "Washington",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-22T09:45:00Z"
  },
  {
    contact_id: 111,
    first_name: "Kevin",
    last_name: "Brooks",
    job_title_raw: "Director of Teaching and Learning",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "kbrooks@wcuusd.org",
    phone_main: "(802) 229-0553",
    district_name: "Washington Central UUSD",
    county: "Washington",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-18T11:20:00Z"
  },
  {
    contact_id: 112,
    first_name: "Amanda",
    last_name: "Lee",
    job_title_raw: "Director of Curriculum",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "alee@lnsd.org",
    phone_main: "(802) 851-1178",
    district_name: "Lamoille North SU",
    county: "Lamoille",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-20T16:15:00Z"
  },
  {
    contact_id: 113,
    first_name: "Christopher",
    last_name: "Hale",
    job_title_raw: "Curriculum Director",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "chale@lsuu.org",
    phone_main: "(802) 888-4541",
    district_name: "Lamoille South SU",
    county: "Lamoille",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-21T10:45:00Z"
  },
  {
    contact_id: 114,
    first_name: "Susan",
    last_name: "Wright",
    job_title_raw: "Director of Instruction",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "swright@fwsu.org",
    phone_main: "(802) 848-7661",
    district_name: "Franklin West SU",
    county: "Franklin",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-19T13:30:00Z"
  },
  {
    contact_id: 115,
    first_name: "Daniel",
    last_name: "Kim",
    job_title_raw: "Director of Student Learning",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "dkim@fnesu.org",
    phone_main: "(802) 933-2550",
    district_name: "Franklin Northeast SU",
    county: "Franklin",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-23T09:10:00Z"
  },
  {
    contact_id: 116,
    first_name: "Margaret",
    last_name: "Thatcher",
    job_title_raw: "Assistant Superintendent of Teaching and Learning",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "mthatcher@acsdvt.org",
    phone_main: "(802) 382-1274",
    district_name: "Addison Central SD",
    county: "Addison",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-24T14:55:00Z"
  },
  {
    contact_id: 117,
    first_name: "Andrew",
    last_name: "Scott",
    job_title_raw: "Director of Learning",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "ascott@anwsd.org",
    phone_main: "(802) 877-3332",
    district_name: "Addison Northwest SD",
    county: "Addison",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-20T12:00:00Z"
  },
  {
    contact_id: 118,
    first_name: "Karen",
    last_name: "Davis",
    job_title_raw: "Director of Curriculum and Instruction",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "kdavis@rcpsvt.org",
    phone_main: "(802) 773-1900",
    district_name: "Rutland City SD",
    county: "Rutland",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-22T08:30:00Z"
  },
  {
    contact_id: 119,
    first_name: "Brian",
    last_name: "Kelly",
    job_title_raw: "Director of Curriculum",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "bkelly@slatevalley.org",
    phone_main: "(802) 265-4905",
    district_name: "Slate Valley UUSD",
    county: "Rutland",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-19T15:40:00Z"
  },
  {
    contact_id: 120,
    first_name: "Jessica",
    last_name: "Moore",
    job_title_raw: "Director of Curriculum, Instruction and Assessment",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "jmoore@wsesu.org",
    phone_main: "(802) 254-3730",
    district_name: "Windham Southeast SU",
    county: "Windham",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-21T11:15:00Z"
  },
  {
    contact_id: 121,
    first_name: "Nancy",
    last_name: "Fitzgerald",
    job_title_raw: "Assistant Superintendent",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "nfitzgerald@hsdvt.com",
    phone_main: "(802) 295-8600",
    district_name: "Hartford SD",
    county: "Windsor",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-23T10:05:00Z"
  },
  {
    contact_id: 122,
    first_name: "Steven",
    last_name: "Baker",
    job_title_raw: "Director of Academics",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "sbaker@kingdomeast.org",
    phone_main: "(802) 626-6100",
    district_name: "Kingdom East SD",
    county: "Caledonia",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-24T09:25:00Z"
  },
  {
    contact_id: 123,
    first_name: "Laura",
    last_name: "Simmons",
    job_title_raw: "Curriculum Director",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "lsimmons@ncsuvt.org",
    phone_main: "(802) 334-5847",
    district_name: "North Country SU",
    county: "Orleans",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-20T14:00:00Z"
  },
  {
    contact_id: 124,
    first_name: "Stephanie",
    last_name: "Barton",
    job_title_raw: "Director of Curriculum",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "sbarton@rnesu.org",
    phone_main: "(802) 247-5757",
    district_name: "Rutland Northeast SU",
    county: "Rutland",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T08:00:00Z"
  },
  {
    contact_id: 125,
    first_name: "David",
    last_name: "Younce",
    job_title_raw: "Director of Curriculum & Instruction",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "dyounce@grcsu.org",
    phone_main: "(802) 775-4342",
    district_name: "Greater Rutland County SU",
    county: "Rutland",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T08:15:00Z"
  },
  {
    contact_id: 126,
    first_name: "Angie",
    last_name: "Lorio",
    job_title_raw: "Director of Instruction",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "alorio@wsesu.net",
    phone_main: "(802) 674-2144",
    district_name: "Windsor Southeast SU",
    county: "Windsor",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T08:30:00Z"
  },
  {
    contact_id: 127,
    first_name: "Sherry",
    last_name: "Sousa",
    job_title_raw: "Director of Curriculum",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "ssousa@mtnviews.org",
    phone_main: "(802) 457-1213",
    district_name: "Mountain Views SU",
    county: "Windsor",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T09:00:00Z"
  },
  {
    contact_id: 128,
    first_name: "Emilie",
    last_name: "Knibbs",
    job_title_raw: "Asst. Superintendent",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "eknibbs@oesu.org",
    phone_main: "(802) 222-5216",
    district_name: "Orange East SU",
    county: "Orange",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T09:15:00Z"
  },
  {
    contact_id: 129,
    first_name: "Heather",
    last_name: "Boucher",
    job_title_raw: "Curriculum Coordinator",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "hboucher@ossw.org",
    phone_main: "(802) 728-5052",
    district_name: "Orange Southwest SD",
    county: "Orange",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T09:30:00Z"
  },
  {
    contact_id: 130,
    first_name: "Keith",
    last_name: "Thompson",
    job_title_raw: "Director of Teaching & Learning",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "kthompson@wrvsu.org",
    phone_main: "(802) 763-8840",
    district_name: "White River Valley SU",
    county: "Windsor",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T09:45:00Z"
  },
  {
    contact_id: 131,
    first_name: "Des",
    last_name: "Hertz",
    job_title_raw: "Curriculum Director",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "dhertz@ccsu.org",
    phone_main: "(802) 684-3801",
    district_name: "Caledonia Central SU",
    county: "Caledonia",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T10:00:00Z"
  },
  {
    contact_id: 132,
    first_name: "Jennifer",
    last_name: "Lawcewicz",
    job_title_raw: "Director of Curriculum",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "jlawcewicz@ensu.net",
    phone_main: "(802) 266-3330",
    district_name: "Essex North SU",
    county: "Essex",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T10:15:00Z"
  },
  {
    contact_id: 133,
    first_name: "Mike",
    last_name: "Moriarty",
    job_title_raw: "Director of Instruction",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "mmoriarty@ocsu.org",
    phone_main: "(802) 525-1204",
    district_name: "Orleans Central SU",
    county: "Orleans",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T10:30:00Z"
  },
  {
    contact_id: 134,
    first_name: "Adam",
    last_name: "Rosenberg",
    job_title_raw: "Director of Learning",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "arosenberg@ossu.org",
    phone_main: "(802) 472-6531",
    district_name: "Orleans Southwest SU",
    county: "Orleans",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T10:45:00Z"
  },
  {
    contact_id: 135,
    first_name: "Megan",
    last_name: "Gruman",
    job_title_raw: "Curriculum Director",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "mgruman@gisu.org",
    phone_main: "(802) 372-6921",
    district_name: "Grand Isle SU",
    county: "Grand Isle",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T11:00:00Z"
  },
  {
    contact_id: 136,
    first_name: "Mary",
    last_name: "Barton",
    job_title_raw: "Director of Curriculum",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "mbarton@trsu.org",
    phone_main: "(802) 228-1313",
    district_name: "Two Rivers SU",
    county: "Windsor",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T11:15:00Z"
  },
  {
    contact_id: 137,
    first_name: "Sherri",
    last_name: "Nichols",
    job_title_raw: "Director of Curriculum",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "snichols@ssdvt.org",
    phone_main: "(802) 885-5100",
    district_name: "Springfield SD",
    county: "Windsor",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T11:30:00Z"
  },
  {
    contact_id: 138,
    first_name: "Sarah",
    last_name: "Hathaway",
    job_title_raw: "Director of Academics",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "shathaway@stjsd.org",
    phone_main: "(802) 748-5800",
    district_name: "St. Johnsbury SD",
    county: "Caledonia",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T11:45:00Z"
  },
  {
    contact_id: 139,
    first_name: "Keri",
    last_name: "Bristow",
    job_title_raw: "Curriculum Coordinator",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "kbristow@rivendellschool.org",
    phone_main: "(603) 353-2170",
    district_name: "Rivendell Interstate SD",
    county: "Orange",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T12:00:00Z"
  },
  {
    contact_id: 140,
    first_name: "Patrick",
    last_name: "Reen",
    job_title_raw: "Director of Teaching & Learning",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "preen@mausd.org",
    phone_main: "(802) 453-3657",
    district_name: "Mount Abraham USD",
    county: "Addison",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T12:15:00Z"
  },
  {
    contact_id: 141,
    first_name: "Alexis",
    last_name: "Katz",
    job_title_raw: "Assistant Superintendent",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "akatz@maplerun.org",
    phone_main: "(802) 524-2600",
    district_name: "Maple Run USD",
    county: "Franklin",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T12:30:00Z"
  },
  {
    contact_id: 142,
    first_name: "Gwen",
    last_name: "Carmolli",
    job_title_raw: "Director of Curriculum & Instruction",
    role_category: RoleCategory.DISTRICT_PD_LEAD,
    email: "gcarmolli@csdvt.org",
    phone_main: "(802) 264-5999",
    district_name: "Colchester SD",
    county: "Chittenden",
    school_level: SchoolLevel.DISTRICT_WIDE,
    last_updated: "2025-11-25T12:45:00Z"
  }
];

export const VECA_SYSTEM_INSTRUCTION = `
You are the VECA (Vermont Education Contact Aggregator) Intelligent Agent.
Your role is to assist users in understanding the Vermont education landscape, specifically regarding Professional Development (PD) contacts.

Context:
- In Vermont, "Head of PD" is rarely a standalone title in elementary schools.
- You identify relevant contacts by looking for "Curriculum Directors" (SU level) or "Principals" (School level).
- You utilize the Agency of Education (AOE) directory and Supervisory Union websites.

Your capabilities:
- You can explain how data is scraped (Section 3.1 of SRS).
- You can help map roles (e.g., "Director of Learning" -> "District PD Lead").
- You strictly adhere to TUC branding tone: Professional, Academic, Efficient.

If asked about specific data, explain that you are currently in Phase 1 (Foundation Setup) and are using a preliminary dataset.
`;