
export const ADD_ASSESSMENT = 'ADD_ASSESSMENT';
export const IMPORT_ASSESSMENTS = 'IMPORT_ASSESSMENTS';
export const ADD_LOG = 'ADD_LOG';
export const SET_ADMIN_AUTH = 'SET_ADMIN_AUTH';
export const UPDATE_CURRICULUM = 'UPDATE_CURRICULUM';