import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { AlertTriangle, Monitor, Activity, Shield } from 'lucide-react';
import { clsx } from 'clsx';
import { formatDistanceToNow } from 'date-fns';
import { RadialBarChart, RadialBar, ResponsiveContainer } from 'recharts';
function UtilGauge({ pct, label }) {
    const color = pct > 80 ? '#FF4444' : pct > 60 ? '#FFB800' : '#00FF87';
    return (_jsxs("div", { className: "noc-card p-4 flex flex-col items-center", children: [_jsxs("div", { className: "relative w-20 h-20", children: [_jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsx(RadialBarChart, { cx: "50%", cy: "50%", innerRadius: "55%", outerRadius: "90%", data: [{ value: pct, fill: color }], startAngle: 90, endAngle: 90 - pct * 3.6, children: _jsx(RadialBar, { dataKey: "value", cornerRadius: 4 }) }) }), _jsx("div", { className: "absolute inset-0 flex flex-col items-center justify-center", children: _jsxs("span", { className: "font-mono-display text-sm font-bold", style: { color }, children: [Math.round(pct), "%"] }) })] }), _jsx("p", { className: "text-xs font-mono-code text-slate-400 mt-2 tracking-wider text-center", children: label })] }));
}
function StatCard({ icon: Icon, label, value, sub, color }) {
    return (_jsxs("div", { className: "noc-card p-4", children: [_jsxs("div", { className: "flex items-start justify-between mb-3", children: [_jsx("span", { className: "text-xs font-mono-code text-slate-500 tracking-widest", children: label }), _jsx("div", { className: "w-7 h-7 rounded flex items-center justify-center", style: { background: `${color}15`, border: `1px solid ${color}30` }, children: _jsx(Icon, { size: 13, style: { color } }) })] }), _jsx("div", { className: "font-mono-display text-2xl", style: { color }, children: value }), sub && _jsx("p", { className: "text-xs text-slate-500 mt-1", children: sub })] }));
}
export function OverviewPage() {
    const { data: health, isLoading } = useQuery({ queryKey: ['health'], queryFn: api.health });
    const { data: alerts = [] } = useQuery({ queryKey: ['alerts', 'ACTIVE'], queryFn: () => api.alerts.list(undefined, 'ACTIVE') });
    const { data: interfaces = [] } = useQuery({ queryKey: ['bw-interfaces'], queryFn: api.bandwidth.interfaces });
    if (isLoading)
        return (_jsx("div", { className: "flex items-center justify-center h-64", children: _jsx("div", { className: "font-mono-display text-gold/40 tracking-widest animate-pulse", children: "LOADING NETWORK STATE..." }) }));
    const criticals = alerts.filter(a => a.severity === 'CRITICAL');
    const warnings = alerts.filter(a => a.severity === 'WARNING');
    const wanIface = interfaces.find(i => i.name === 'WAN-Upstream');
    return (_jsxs("div", { className: "space-y-6 animate-fade-in", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "font-mono-display text-xl text-gold tracking-widest", children: "NETWORK OVERVIEW" }), _jsxs("p", { className: "text-xs text-slate-500 font-mono-code mt-0.5", children: ["Last updated: ", health?.lastScan ? formatDistanceToNow(new Date(health.lastScan), { addSuffix: true }) : '—'] })] }), criticals.length > 0 && (_jsxs("div", { className: "flex items-center gap-2 px-3 py-1.5 rounded text-xs font-mono-code", style: { background: 'rgba(255,68,68,0.1)', border: '1px solid rgba(255,68,68,0.3)', color: '#FF4444' }, children: [_jsx(AlertTriangle, { size: 12 }), criticals.length, " CRITICAL ALERT", criticals.length > 1 ? 'S' : ''] }))] }), _jsxs("div", { className: "grid grid-cols-2 lg:grid-cols-4 gap-4", children: [_jsx(StatCard, { icon: Monitor, label: "ACTIVE DEVICES", value: health?.activeDevices ?? '—', color: "#00FF87", sub: `of ${(health?.activeDevices ?? 0) + 3} total registered` }), _jsx(StatCard, { icon: AlertTriangle, label: "ROGUE DEVICES", value: health?.rogueDevices ?? '—', color: health?.rogueDevices ? '#FF4444' : '#00FF87', sub: health?.rogueDevices ? 'Immediate action required' : 'All devices authorised' }), _jsx(StatCard, { icon: Shield, label: "ACTIVE ALERTS", value: health?.activeAlerts ?? '—', color: health?.activeAlerts ? '#FFB800' : '#00FF87', sub: `${criticals.length} critical · ${warnings.length} warning` }), _jsx(StatCard, { icon: Activity, label: "WAN UTILISATION", value: `${health?.wanUtilisationPct?.toFixed(1) ?? '—'}%`, color: health?.wanUtilisationPct ?? 0 > 80 ? '#FF4444' : '#00FF87', sub: "100 Mbps uplink capacity" })] }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsxs("div", { className: "noc-card p-5", children: [_jsx("h2", { className: "font-mono-code text-xs text-slate-400 tracking-widest mb-4", children: "INTERFACE UTILISATION" }), _jsx("div", { className: "grid grid-cols-3 gap-2", children: interfaces.slice(0, 5).map(iface => (_jsx(UtilGauge, { pct: iface.utilisationPct, label: iface.name.replace('WiFi-', '') }, iface.id))) })] }), _jsxs("div", { className: "lg:col-span-2 noc-card p-5", children: [_jsx("h2", { className: "font-mono-code text-xs text-slate-400 tracking-widest mb-4", children: "ACTIVE ALERTS" }), alerts.length === 0 ? (_jsx("div", { className: "flex items-center justify-center h-32 text-green-400 font-mono-code text-xs", children: "\u2713 NO ACTIVE ALERTS" })) : (_jsx("div", { className: "space-y-2", children: alerts.slice(0, 5).map(a => (_jsxs("div", { className: "flex items-start gap-3 p-3 rounded", style: { background: 'rgba(0,0,0,0.2)', border: '1px solid rgba(255,255,255,0.05)' }, children: [_jsx("span", { className: "text-xs font-mono-code px-2 py-0.5 rounded shrink-0 mt-0.5", style: {
                                                background: a.severity === 'CRITICAL' ? 'rgba(255,68,68,0.15)' : a.severity === 'WARNING' ? 'rgba(255,184,0,0.15)' : 'rgba(0,207,255,0.15)',
                                                color: a.severity === 'CRITICAL' ? '#FF4444' : a.severity === 'WARNING' ? '#FFB800' : '#00CFFF',
                                                border: `1px solid ${a.severity === 'CRITICAL' ? 'rgba(255,68,68,0.3)' : a.severity === 'WARNING' ? 'rgba(255,184,0,0.3)' : 'rgba(0,207,255,0.3)'}`
                                            }, children: a.severity }), _jsxs("div", { className: "min-w-0", children: [_jsx("p", { className: "text-sm text-slate-200 truncate", children: a.title }), _jsx("p", { className: "text-xs text-slate-500 mt-0.5 truncate", children: a.message })] }), _jsx("span", { className: "text-xs text-slate-600 shrink-0 font-mono-code ml-auto", children: formatDistanceToNow(new Date(a.createdAt), { addSuffix: true }) })] }, a.id))) }))] })] }), _jsxs("div", { className: "noc-card p-4", children: [_jsx("h2", { className: "font-mono-code text-xs text-slate-400 tracking-widest mb-3", children: "SYSTEM STATUS" }), _jsx("div", { className: "flex items-center gap-8 flex-wrap", children: [
                            { label: 'DATABASE', ok: health?.dbOk },
                            { label: 'REDIS', ok: health?.redisOk },
                            { label: 'SCANNER', ok: true },
                            { label: 'API', ok: true },
                            { label: 'WEBSOCKET', ok: true },
                        ].map(s => (_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: clsx('pulse-dot', s.ok ? 'green' : 'red') }), _jsx("span", { className: "text-xs font-mono-code text-slate-400", children: s.label }), _jsx("span", { className: "text-xs font-mono-code", style: { color: s.ok ? '#00FF87' : '#FF4444' }, children: s.ok ? 'OK' : 'DOWN' })] }, s.label))) })] })] }));
}
