import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
// ── AlertsPage ────────────────────────────────────────────────────────
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { CheckCircle, AlertTriangle, AlertCircle, Info } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
function SeverityIcon({ s }) {
    if (s === 'CRITICAL')
        return _jsx(AlertTriangle, { size: 14, style: { color: '#FF4444' } });
    if (s === 'WARNING')
        return _jsx(AlertCircle, { size: 14, style: { color: '#FFB800' } });
    return _jsx(Info, { size: 14, style: { color: '#00CFFF' } });
}
function AckModal({ alert, onClose }) {
    const [note, setNote] = useState('');
    const qc = useQueryClient();
    const mut = useMutation({
        mutationFn: () => api.alerts.ack(alert.id, note),
        onSuccess: () => { qc.invalidateQueries({ queryKey: ['alerts'] }); qc.invalidateQueries({ queryKey: ['health'] }); onClose(); }
    });
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm", children: _jsxs("div", { className: "noc-card w-full max-w-md p-6", children: [_jsxs("h3", { className: "font-mono-code text-xs text-slate-400 tracking-widest mb-3", children: ["ACKNOWLEDGE ALERT #", alert.id] }), _jsx("p", { className: "text-sm text-slate-200 mb-1", children: alert.title }), _jsx("p", { className: "text-xs text-slate-500 mb-4", children: alert.message }), _jsx("label", { className: "block text-xs font-mono-code text-slate-400 tracking-widest mb-1.5", children: "ACK NOTE (REQUIRED)" }), _jsx("textarea", { value: note, onChange: e => setNote(e.target.value), rows: 3, placeholder: "Describe the action taken or why this alert is being acknowledged...", className: "w-full bg-black/30 border border-white/10 rounded px-3 py-2 text-sm text-slate-200 font-mono-code mb-4 focus:outline-none focus:border-gold/40 resize-none" }), _jsxs("div", { className: "flex gap-3", children: [_jsx("button", { onClick: onClose, className: "flex-1 py-2 text-xs font-mono-code text-slate-400 border border-white/10 rounded", children: "CANCEL" }), _jsx("button", { onClick: () => mut.mutate(), disabled: !note.trim() || mut.isPending, className: "flex-1 py-2 text-xs font-mono-code rounded disabled:opacity-40", style: { background: 'rgba(0,255,135,0.1)', border: '1px solid rgba(0,255,135,0.3)', color: '#00FF87' }, children: mut.isPending ? 'ACKNOWLEDGING...' : 'ACKNOWLEDGE' })] })] }) }));
}
export function AlertsPage() {
    const [filter, setFilter] = useState('ACTIVE');
    const [sevFilter, setSevFilter] = useState('');
    const [acking, setAcking] = useState(null);
    const { data: alerts = [] } = useQuery({
        queryKey: ['alerts', filter, sevFilter],
        queryFn: () => api.alerts.list(sevFilter || undefined, filter === 'ALL' ? undefined : filter),
        refetchInterval: 15_000,
    });
    return (_jsxs("div", { className: "space-y-5 animate-fade-in", children: [_jsxs("div", { children: [_jsx("h1", { className: "font-mono-display text-xl text-gold tracking-widest", children: "ALERTS" }), _jsxs("p", { className: "text-xs text-slate-500 font-mono-code mt-0.5", children: [alerts.filter(a => a.status === 'ACTIVE').length, " active"] })] }), _jsxs("div", { className: "flex items-center gap-3 flex-wrap", children: [['ALL', 'ACTIVE', 'ACKNOWLEDGED'].map(f => (_jsx("button", { onClick: () => setFilter(f), className: "px-3 py-1.5 rounded text-xs font-mono-code tracking-wider transition-all", style: filter === f
                            ? { background: 'rgba(200,146,10,0.15)', border: '1px solid rgba(200,146,10,0.4)', color: '#C8920A' }
                            : { border: '1px solid rgba(255,255,255,0.08)', color: '#64748b' }, children: f }, f))), _jsx("div", { className: "w-px h-5 bg-white/10" }), ['', 'CRITICAL', 'WARNING', 'INFO'].map(s => (_jsx("button", { onClick: () => setSevFilter(s), className: "px-3 py-1.5 rounded text-xs font-mono-code tracking-wider transition-all", style: sevFilter === s
                            ? { background: 'rgba(200,146,10,0.15)', border: '1px solid rgba(200,146,10,0.4)', color: '#C8920A' }
                            : { border: '1px solid rgba(255,255,255,0.08)', color: '#64748b' }, children: s || 'ALL SEV.' }, s)))] }), _jsx("div", { className: "space-y-2", children: alerts.length === 0 ? (_jsxs("div", { className: "noc-card p-12 text-center", children: [_jsx(CheckCircle, { size: 32, className: "mx-auto mb-3", style: { color: '#00FF87' } }), _jsx("p", { className: "font-mono-code text-xs text-slate-500", children: "NO ALERTS MATCHING FILTER" })] })) : (alerts.map(a => (_jsxs("div", { className: "noc-card p-4 flex items-start gap-4", style: { borderLeftWidth: '3px', borderLeftColor: a.severity === 'CRITICAL' ? '#FF4444' : a.severity === 'WARNING' ? '#FFB800' : '#00CFFF' }, children: [_jsx(SeverityIcon, { s: a.severity }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex items-center gap-3 mb-1", children: [_jsx("span", { className: "text-sm text-slate-200 font-medium", children: a.title }), _jsx("span", { className: "text-xs font-mono-code text-slate-600", children: a.alertType })] }), _jsx("p", { className: "text-xs text-slate-400", children: a.message }), a.status === 'ACKNOWLEDGED' && (_jsxs("p", { className: "text-xs text-slate-600 mt-1 font-mono-code", children: ["ACK'd by ", a.ackedBy, " \u00B7 ", a.ackNote] }))] }), _jsxs("div", { className: "text-right shrink-0", children: [_jsx("p", { className: "text-xs text-slate-600 font-mono-code mb-2", children: formatDistanceToNow(new Date(a.createdAt), { addSuffix: true }) }), a.status === 'ACTIVE' && (_jsx("button", { onClick: () => setAcking(a), className: "px-3 py-1 rounded text-xs font-mono-code transition-colors", style: { background: 'rgba(0,255,135,0.08)', border: '1px solid rgba(0,255,135,0.2)', color: '#00FF87' }, children: "ACK" }))] })] }, a.id)))) }), acking && _jsx(AckModal, { alert: acking, onClose: () => setAcking(null) })] }));
}
// ── ControlPage ───────────────────────────────────────────────────────
import { Unlock, Copy, Check } from 'lucide-react';
export function ControlPage() {
    const [scriptModal, setScriptModal] = useState(null);
    const [copied, setCopied] = useState(false);
    const qc = useQueryClient();
    const { data: blocks = [] } = useQuery({ queryKey: ['blocks'], queryFn: api.control.list, refetchInterval: 30_000 });
    const unblockMut = useMutation({
        mutationFn: (id) => api.control.unblock(id),
        onSuccess: () => { qc.invalidateQueries({ queryKey: ['blocks'] }); qc.invalidateQueries({ queryKey: ['devices'] }); }
    });
    function copyScript(script) {
        navigator.clipboard.writeText(script).then(() => { setCopied(true); setTimeout(() => setCopied(false), 2000); });
    }
    return (_jsxs("div", { className: "space-y-5 animate-fade-in", children: [_jsxs("div", { children: [_jsx("h1", { className: "font-mono-display text-xl text-gold tracking-widest", children: "DEVICE CONTROL" }), _jsxs("p", { className: "text-xs text-slate-500 font-mono-code mt-0.5", children: [blocks.filter(b => b.active).length, " active block", blocks.filter(b => b.active).length !== 1 ? 's' : '', " \u00B7 Use the Devices panel to block a device"] })] }), _jsx("div", { className: "noc-card p-4 text-xs font-mono-code", style: { borderColor: 'rgba(255,184,0,0.2)', background: 'rgba(255,184,0,0.03)' }, children: _jsxs("p", { className: "text-amber-400 flex items-center gap-2", children: [_jsx(AlertTriangle, { size: 12 }), "IMPORTANT: Blocking a device generates an iptables script. SSH to the campus gateway and apply it as root."] }) }), _jsxs("div", { className: "noc-card overflow-hidden", children: [_jsx("div", { className: "px-5 py-3 border-b border-gold/10", children: _jsx("h2", { className: "font-mono-code text-xs text-slate-400 tracking-widest", children: "BLOCK LIST" }) }), _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsx("tr", { style: { borderBottom: '1px solid rgba(200,146,10,0.1)' }, children: ['ID', 'MAC', 'REASON', 'BLOCKED BY', 'BLOCKED AT', 'STATUS', 'ACTIONS'].map(h => (_jsx("th", { className: "text-left px-4 py-3 text-xs font-mono-code text-slate-500 tracking-widest", children: h }, h))) }) }), _jsx("tbody", { children: blocks.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 7, className: "text-center py-10 text-slate-500 font-mono-code text-xs", children: "NO BLOCKS CONFIGURED" }) })) : (blocks.map(b => (_jsxs("tr", { style: { borderBottom: '1px solid rgba(255,255,255,0.03)' }, children: [_jsx("td", { className: "px-4 py-3 font-mono-code text-xs text-slate-500", children: b.id }), _jsx("td", { className: "px-4 py-3 font-mono-code text-xs text-scan-blue", children: b.mac }), _jsx("td", { className: "px-4 py-3 text-xs text-slate-400 max-w-xs truncate", children: b.reason }), _jsx("td", { className: "px-4 py-3 text-xs text-slate-400 font-mono-code", children: b.blockedBy }), _jsx("td", { className: "px-4 py-3 text-xs text-slate-500 font-mono-code whitespace-nowrap", children: formatDistanceToNow(new Date(b.blockedAt), { addSuffix: true }) }), _jsx("td", { className: "px-4 py-3", children: _jsx("span", { className: "text-xs font-mono-code px-2 py-0.5 rounded", style: b.active
                                                    ? { background: 'rgba(255,68,68,0.1)', color: '#FF4444', border: '1px solid rgba(255,68,68,0.2)' }
                                                    : { background: 'rgba(100,116,139,0.1)', color: '#64748b', border: '1px solid rgba(100,116,139,0.2)' }, children: b.active ? 'ACTIVE' : 'REMOVED' }) }), _jsx("td", { className: "px-4 py-3", children: _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { onClick: () => setScriptModal(b.script), className: "p-1.5 rounded hover:bg-gold/10 transition-colors", title: "View firewall script", children: _jsx(Copy, { size: 12, className: "text-gold/50 hover:text-gold" }) }), b.active && (_jsx("button", { onClick: () => unblockMut.mutate(b.id), className: "p-1.5 rounded hover:bg-green-500/10 transition-colors", title: "Unblock device", children: _jsx(Unlock, { size: 12, className: "text-green-500/50 hover:text-green-400" }) }))] }) })] }, b.id)))) })] })] }), scriptModal && (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm", children: _jsxs("div", { className: "noc-card w-full max-w-2xl p-6", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h3", { className: "font-mono-code text-xs text-slate-400 tracking-widest", children: "GENERATED FIREWALL SCRIPT" }), _jsxs("button", { onClick: () => copyScript(scriptModal), className: "flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-mono-code", style: { background: 'rgba(200,146,10,0.1)', border: '1px solid rgba(200,146,10,0.3)', color: '#C8920A' }, children: [copied ? _jsx(Check, { size: 11 }) : _jsx(Copy, { size: 11 }), copied ? 'COPIED' : 'COPY'] })] }), _jsx("pre", { className: "bg-black/40 rounded p-4 text-xs font-mono-code text-green-400 overflow-auto max-h-80 whitespace-pre", children: scriptModal }), _jsx("button", { onClick: () => setScriptModal(null), className: "mt-4 w-full py-2 text-xs font-mono-code text-slate-400 border border-white/10 rounded hover:border-white/20", children: "CLOSE" })] }) }))] }));
}
export function AuditPage() {
    const [actionFilter, setActionFilter] = useState('');
    const { data: log = [] } = useQuery({
        queryKey: ['audit', actionFilter],
        queryFn: () => api.audit.list(actionFilter || undefined),
        refetchInterval: 30_000,
    });
    const ACTION_TYPES = ['', 'BLOCK', 'UNBLOCK', 'ANNOTATE', 'ACK_ALERT', 'SCAN'];
    const ACTION_COLOURS = {
        BLOCK: '#FF4444', UNBLOCK: '#00FF87', ANNOTATE: '#C8920A',
        ACK_ALERT: '#00CFFF', SCAN: '#FFB800'
    };
    return (_jsxs("div", { className: "space-y-5 animate-fade-in", children: [_jsxs("div", { children: [_jsx("h1", { className: "font-mono-display text-xl text-gold tracking-widest", children: "AUDIT LOG" }), _jsxs("p", { className: "text-xs text-slate-500 font-mono-code mt-0.5", children: [log.length, " entries \u00B7 append-only \u00B7 5 year retention"] })] }), _jsx("div", { className: "flex gap-2 flex-wrap", children: ACTION_TYPES.map(a => (_jsx("button", { onClick: () => setActionFilter(a), className: "px-3 py-1.5 rounded text-xs font-mono-code tracking-wider transition-all", style: actionFilter === a
                        ? { background: 'rgba(200,146,10,0.15)', border: '1px solid rgba(200,146,10,0.4)', color: '#C8920A' }
                        : { border: '1px solid rgba(255,255,255,0.08)', color: '#64748b' }, children: a || 'ALL ACTIONS' }, a))) }), _jsx("div", { className: "noc-card overflow-hidden", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsx("tr", { style: { borderBottom: '1px solid rgba(200,146,10,0.1)' }, children: ['ID', 'ACTOR', 'ACTION', 'TARGET', 'REASON', 'TIMESTAMP'].map(h => (_jsx("th", { className: "text-left px-4 py-3 text-xs font-mono-code text-slate-500 tracking-widest", children: h }, h))) }) }), _jsx("tbody", { children: log.length === 0 ? (_jsx("tr", { children: _jsx("td", { colSpan: 6, className: "text-center py-10 text-slate-500 font-mono-code text-xs", children: "NO AUDIT ENTRIES" }) })) : (log.map((e, i) => (_jsxs("tr", { style: { borderBottom: '1px solid rgba(255,255,255,0.03)', background: i % 2 === 0 ? 'transparent' : 'rgba(0,0,0,0.1)' }, children: [_jsx("td", { className: "px-4 py-3 font-mono-code text-xs text-slate-600", children: e.id }), _jsx("td", { className: "px-4 py-3 font-mono-code text-xs text-gold/80", children: e.actor }), _jsx("td", { className: "px-4 py-3", children: _jsx("span", { className: "text-xs font-mono-code px-2 py-0.5 rounded", style: { color: ACTION_COLOURS[e.actionType] ?? '#64748b', background: `${ACTION_COLOURS[e.actionType] ?? '#64748b'}15`, border: `1px solid ${ACTION_COLOURS[e.actionType] ?? '#64748b'}30` }, children: e.actionType }) }), _jsx("td", { className: "px-4 py-3 font-mono-code text-xs text-scan-blue", children: e.targetId }), _jsx("td", { className: "px-4 py-3 text-xs text-slate-400 max-w-xs truncate", children: e.reason }), _jsx("td", { className: "px-4 py-3 text-xs text-slate-500 font-mono-code whitespace-nowrap", children: formatDistanceToNow(new Date(e.createdAt), { addSuffix: true }) })] }, e.id)))) })] }) })] }));
}
