import { test, expect } from '@playwright/test';

/**
 * Generator flow tests — form interaction, validation, state machine transitions.
 */

const AUTH_KEY  = 'tuc_auth_youtube-genie';
const USER_KEY  = 'youtube-genie_user';
const FAKE_USER = JSON.stringify({ id: 'test-001', name: 'TUC Test', email: 'test@techbridge.edu.gh' });

test.use({
  // Inject auth bypass before every test in this file
});

async function loginAndGoto(page: import('@playwright/test').Page, path = '/youtube-genie/') {
  await page.addInitScript(({ authKey, userKey, fakeUser }) => {
    sessionStorage.setItem(authKey, '1');
    localStorage.setItem(userKey, fakeUser);
    // Clear any saved form data so tests start with defaults
    localStorage.removeItem('youtube-genie-form-data');
  }, { authKey: AUTH_KEY, userKey: USER_KEY, fakeUser: FAKE_USER });
  await page.goto(path);
}

test.describe('Generator form', () => {
  test('shows all required input fields', async ({ page }) => {
    await loginAndGoto(page);
    await expect(page.getByLabel(/Song Title/i)).toBeVisible();
    await expect(page.getByLabel(/Artist Name/i)).toBeVisible();
    await expect(page.getByLabel(/YouTube Channel Handle/i)).toBeVisible();
    await expect(page.getByLabel(/Genres/i)).toBeVisible();
    await expect(page.getByLabel(/Vibe Keywords/i)).toBeVisible();
    await expect(page.getByLabel(/Lyrics/i)).toBeVisible();
  });

  test('shows Generate Description button', async ({ page }) => {
    await loginAndGoto(page);
    await expect(page.getByRole('button', { name: /Generate Description/i })).toBeVisible();
  });

  test('shows output panel placeholder when no result yet', async ({ page }) => {
    await loginAndGoto(page);
    await expect(page.getByRole('heading', { name: /Generated Description/i })).toBeVisible();
    await expect(page.getByText(/Your generated description will appear here/i)).toBeVisible();
  });

  test('form validation — empty required fields show errors on submit', async ({ page }) => {
    await loginAndGoto(page);

    // Clear all fields first
    await page.getByLabel(/Song Title/i).fill('');
    await page.getByLabel(/Artist Name/i).fill('');
    await page.getByLabel(/YouTube Channel Handle/i).fill('');
    await page.getByLabel(/Genres/i).fill('');
    await page.getByLabel(/Vibe Keywords/i).fill('');
    await page.getByLabel(/Lyrics/i).fill('');

    await page.getByRole('button', { name: /Generate Description/i }).click();

    // At least one error message should appear
    const errors = page.locator('[class*="red"], [class*="error"]');
    await expect(errors.first()).toBeVisible();
  });

  test('Clear Form button resets fields to empty', async ({ page }) => {
    await loginAndGoto(page);
    // Type something in Song Title
    await page.getByLabel(/Song Title/i).fill('My Test Song');
    await page.getByRole('button', { name: /Clear Form/i }).click();

    const value = await page.getByLabel(/Song Title/i).inputValue();
    expect(value).toBe('');
  });

  test('Generate Another button appears after successful generation', async ({ page }) => {
    await loginAndGoto(page);

    // Mock the /api/generate endpoint so we don't need a real AI call
    await page.route('**/api/generate*', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          candidates: [{
            content: {
              parts: [{ text: JSON.stringify({ description: 'Test YouTube description generated by mock.' }) }]
            }
          }]
        }),
      });
    });

    // Fill minimum required fields
    await page.getByLabel(/Song Title/i).fill('Mock Song');
    await page.getByLabel(/Artist Name/i).fill('Mock Artist');
    await page.getByLabel(/YouTube Channel Handle/i).fill('@MockChannel');
    await page.getByLabel(/Genres/i).fill('Pop');
    await page.getByLabel(/Vibe Keywords/i).fill('Upbeat, energetic');
    await page.getByLabel(/Lyrics/i).fill('These are the lyrics to the mock song. '.repeat(5));

    await page.getByRole('button', { name: /Generate Description/i }).click();

    // Loading state should appear briefly
    await expect(page.getByText(/Generating Description/i)).toBeVisible({ timeout: 3000 }).catch(() => {
      // Loading may complete too fast with mock — that is fine
    });

    // After completion, Generate Another should appear
    await expect(page.getByRole('button', { name: /Generate Another/i })).toBeVisible({ timeout: 10000 });
  });

  test('Generate Another resets to setup state', async ({ page }) => {
    await loginAndGoto(page);

    await page.route('**/api/generate*', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          candidates: [{
            content: { parts: [{ text: JSON.stringify({ description: 'Mock output.' }) }] }
          }]
        }),
      });
    });

    await page.getByLabel(/Song Title/i).fill('Mock Song');
    await page.getByLabel(/Artist Name/i).fill('Mock Artist');
    await page.getByLabel(/YouTube Channel Handle/i).fill('@MockChannel');
    await page.getByLabel(/Genres/i).fill('Pop');
    await page.getByLabel(/Vibe Keywords/i).fill('Upbeat');
    await page.getByLabel(/Lyrics/i).fill('Lyrics here. '.repeat(6));

    await page.getByRole('button', { name: /Generate Description/i }).click();
    await page.getByRole('button', { name: /Generate Another/i }).waitFor({ timeout: 10000 });
    await page.getByRole('button', { name: /Generate Another/i }).click();

    // Back to setup — Generate Description button is visible again
    await expect(page.getByRole('button', { name: /Generate Description/i })).toBeVisible();
    await expect(page.getByRole('button', { name: /Generate Another/i })).not.toBeVisible();
  });
});
