

import { Category, AppItem } from './types';

export const CATEGORIES: Category[] = [
  Category.Research,
  Category.Development,
  Category.Analysis,
  Category.Education,
];

export const AI_APPLICATIONS: AppItem[] = [
  { id: 1, name: 'agent', title: 'Agent-Led Software Development', description: 'A powerful framework for building and deploying autonomous AI agents.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/agent' },
  { id: 2, name: 'smartscale-1', title: 'SmartScale Presentation', description: 'Interactive presentation tool for educational purposes.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/smartscale-1' },
  { id: 3, name: 'visquiz', title: 'Visual Quiz Master', description: 'AI-powered visual quiz generation and assessment.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/visquiz' },
  { id: 4, name: 'flyer', title: 'AI Flyer Generator', description: 'Create professional flyers instantly with AI.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/flyer' },
  { id: 5, name: 'draft-email', title: 'AI Email Drafter', description: 'Draft professional emails quickly using AI assistance.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/draft-email' },
  { id: 6, name: 'code-reviewer', title: 'AI Code Reviewer', description: 'Automated code analysis to improve quality and find bugs.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/code-reviewer' },
  { id: 7, name: 'refresh', title: 'AI Studio Directive Workflow', description: 'Streamline your AI studio workflows and directives.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/refresh' },
  { id: 8, name: 'jsonpp', title: 'JSON Preprocessor - Fixed', description: 'Format and beautify your JSON data for better readability.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/jsonpp' },
  { id: 9, name: 'programmes', title: 'AUCDT Design Programmes', description: 'Explore design programmes and academic offerings.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/programmes' },
  { id: 10, name: 'fdt', title: 'AUCDT: Fashion Design Brochure', description: 'Interactive brochure for the Fashion Design Technology programme.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/fdt' },
  { id: 11, name: 'myvbci', title: 'myVBCI Camper App', description: 'Companion app for VBCI campers.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/myvbci' },
  { id: 12, name: 'css-validator', title: 'CSS Validator', description: 'An AI-powered tool to validate and optimise your CSS code.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/css-validator' },
  { id: 13, name: 'recruitment', title: 'Interactive Agency Assessment | AUCDT Student Recruitment', description: 'Streamline the student recruitment and assessment process.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/recruitment' },
  { id: 14, name: 'thepitchhub', title: 'The Pitch Hub Ghana - Empowering Entrepreneurs', description: 'Refine your business pitches with AI-driven feedback.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/thepitchhub' },
  { id: 15, name: 'playgrow', title: 'PlayGrow – Smart Fun for Bright Minds', description: 'Educational games and activities for children.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/playgrow' },
  { id: 16, name: 'creoai', title: 'CreoAI', description: 'Advanced AI tools for creative professionals.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/creoai' },
  { id: 17, name: 'clipai', title: 'ClipAI', description: 'AI-powered video clipping and editing tool.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/clipai' },
  { id: 18, name: 'msee', title: 'AUCDT MSEE Mathematics Aptitude Test', description: 'Mathematics aptitude testing platform.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/msee' },
  { id: 19, name: 'qmd', title: 'QMD to Google Slides Converter', description: 'Convert QMD files directly to Google Slides presentations.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/qmd' },
  { id: 20, name: 'notification', title: 'Application Confirmation | AUCDT', description: 'Intelligent notification system for application confirmations.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/notification' },
  { id: 21, name: 'drone-1', title: 'Drone Light Show Simulator', description: 'Intelligent flight control and data acquisition for autonomous drones.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/drone-1', imageUrl: 'https://placehold.co/600x400/EEDCFF/5B21B6/png?text=Drones' },
  { id: 22, name: 'chow', title: 'ChowConnect Admin Dashboard', description: 'Administrative dashboard for ChowConnect services.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/chow', imageUrl: 'https://placehold.co/600x400/D1FAE5/065F46/png?text=Culinary+AI' },
  { id: 23, name: 'triptych', title: 'Cinematic Triptych Generator', description: 'Create artistic triptychs from your photos using AI.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/triptych' },
  { id: 24, name: 'waec', title: 'Mature Students Exam App', description: 'Prepare for WAEC exams with AI-generated quizzes and materials.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/waec' },
  { id: 25, name: 'smartscale', title: 'SmartScale Presentation', description: 'Advanced presentation tools for educators.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/smartscale' },
  { id: 26, name: 'entrainer', title: 'enTrainer - Engage Your Metabolic Health with Music', description: 'Music-based metabolic health engagement tool.', category: Category.Research, url: 'https://ai-tools.techbridge.edu.gh/entrainer' },
  { id: 27, name: 'sino', title: 'Sino-Twi Translator', description: 'An AI platform for research in Sino-African relations and language translation.', category: Category.Research, url: 'https://ai-tools.techbridge.edu.gh/sino' },
  { id: 28, name: 'sashmade', title: 'Sashmade Kente Academy Proposal', description: 'Proposal and planning for the Sashmade Kente Academy.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/sashmade' },
  { id: 29, name: 'quick-guide', title: 'Object Identifier - Accessibility App', description: 'AI-powered object identification for accessibility.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/quick-guide' },
  { id: 30, name: 'thrive', title: 'AUCDT Interactive Marketing Strategy', description: 'Personalised wellness and marketing strategy tools.', category: Category.Research, url: 'https://ai-tools.techbridge.edu.gh/thrive' },
  { id: 31, name: 'expensepro', title: 'ExpensePro', description: 'Smart expense tracking and management.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/expensepro' },
  { id: 32, name: 'rpms', title: 'Rophe Patient Management System', description: 'Comprehensive patient management system.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/rpms' },
  { id: 33, name: 'markai', title: 'MarkAI: Marketing for Non-Marketers', description: 'Automated marketing tools and feedback.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/markai' },
  { id: 34, name: 'hostelmanagement', title: 'Mount Horeb Prayer Center - Hostel Management', description: 'Management system for hostels and accommodation.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/hostelmanagement' },
  { id: 35, name: 'primevaluer', title: 'PrimeValuer Pro', description: 'AI-based real estate valuation and market analysis.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/primevaluer' },
  { id: 36, name: 'ai-dentist', title: 'AI in Dental Diagnostics: A New Vision for Oral Health', description: 'Advanced AI for dental diagnostics and treatment planning.', category: Category.Research, url: 'https://ai-tools.techbridge.edu.gh/ai-dentist', imageUrl: 'https://placehold.co/600x400/DBEAFE/1E40AF/png?text=AI+Dentist' },
  { id: 37, name: 'dictation', title: 'Dictation App', description: 'Transcribe your speech to text with high accuracy in real-time.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/dictation' },
  { id: 38, name: 'pdf-json', title: 'PDF to Assessment JSON Converter', description: 'Convert complex PDF documents into structured JSON data.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/pdf-json' },
  { id: 39, name: 'cards', title: 'AI Birthday Card Generator', description: 'Generate intelligent cards for various occasions.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/cards' },
  { id: 40, name: 'cardai', title: 'AUCDT AI Application Portal', description: 'The central portal for all AI applications.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/cardai' },
  { id: 41, name: 'warrior', title: 'DJ CyStorm - Electric Storm Warrior', description: 'An AI tool for identifying and mitigating security threats.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/warrior' },
  { id: 42, name: 'lifeplan', title: 'Life Planner AI', description: 'AI-driven insights for personal and professional goal setting.', category: Category.Research, url: 'https://ai-tools.techbridge.edu.gh/lifeplan' },
  { id: 43, name: 'games', title: 'Brick Breaker Game', description: 'A collection of educational games powered by artificial intelligence.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/games' },
  { id: 44, name: 'games/1', title: 'Enhanced Brick Breaker Game', description: 'An enhanced version of the classic Brick Breaker game.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/games/1' },
  { id: 45, name: 'games/3', title: 'Enhanced Brick Breaker Game', description: 'Another variation of the Brick Breaker game.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/games/3' },
  { id: 46, name: 'games/4', title: 'Classic Tetris Game', description: 'Play the classic Tetris game powered by AI.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/games/4' },
  { id: 47, name: 'games/2', title: 'Enhanced Brick Breaker Game', description: 'Advanced levels for the Brick Breaker game.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/games/2' },
  { id: 48, name: 'veca', title: 'VECA - Vermont Education Contact Aggregator', description: 'Aggregate and analyse education contact data.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/veca' },
  { id: 49, name: 'youtube', title: 'YouTube Description Genie', description: 'Extract insights and trends from YouTube video data.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/youtube' },
  { id: 50, name: 'dmcd', title: 'dmcdAI', description: 'Advanced AI tools for DMCD applications.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/dmcd' },
  { id: 51, name: 'present', title: '14-Day Sprint Daily Standup - AUCDT', description: 'Manage your daily standups and sprints efficiently.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/present' },
  { id: 52, name: 'mailer', title: 'Deployment Guide: Python Email Sender App', description: 'Smart email composition, summarisation, and scheduling.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/mailer' },
  { id: 53, name: 'prions', title: 'Infographic: The Genetic Revolution in Prion Disease Research', description: 'A tool for analysing data related to prion disease studies.', category: Category.Research, url: 'https://ai-tools.techbridge.edu.gh/prions' },
  { id: 54, name: 'math', title: 'AUCDT Examination Portal', description: 'Solve complex mathematical problems with step-by-step solutions.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/math', imageUrl: 'https://placehold.co/600x400/FEF3C7/92400E/png?text=Math+Solver' },
  { id: 55, name: 'standup', title: 'AI Stand-up & Workshop Prep', description: 'Prepare for workshops and stand-ups with AI assistance.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/standup' },
  { id: 56, name: 'iam', title: 'AUCDT IAM System', description: 'Identity and Access Management system.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/iam' },
  { id: 57, name: 'md2latex', title: 'AUCDT | Markdown to LuaLaTeX Converter', description: 'Convert your Markdown documents into professional LaTeX format.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/md2latex' },
  { id: 58, name: 'enactus', title: 'Enactus CKT-UTAS – Student Social Entrepreneurship', description: 'Platform for student social entrepreneurship projects.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/enactus' },
  { id: 59, name: 'pde', title: 'Modern Product Development Lifecycle', description: 'Manage the product development lifecycle with AI.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/pde' },
  { id: 60, name: 'doculatex', title: 'DocuLaTeX | PDF, MD, HTML to LaTeX Converter', description: 'Convert various document formats to LaTeX.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/doculatex' },
  { id: 61, name: 'pdf-extractor', title: 'PDF Email Extractor', description: 'Pull text, tables, and images from PDF files effortlessly.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/pdf-extractor' },
  { id: 62, name: 'sdf', title: 'Strategic Development Framework', description: 'Framework for strategic development and planning.', category: Category.Research, url: 'https://ai-tools.techbridge.edu.gh/sdf' },
  { id: 63, name: 'nobleai', title: 'Ghana Home Design AI Assistant', description: 'AI assistant for home design and architecture.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/nobleai' },
  { id: 64, name: 'smartpresent', title: 'SmartScale Presenter', description: 'Advanced presentation tool for professionals.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/smartpresent' },
  { id: 65, name: 'drive-revenue', title: 'Unlock Your Potential: The 15-Minute AI Agent Masterclass', description: 'Analyse market trends to uncover revenue growth opportunities.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/drive-revenue' },
  { id: 66, name: 'training-evaluator', title: 'Office Training Evaluation', description: 'Assess the effectiveness of training programmes with data analysis.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/training-evaluator' },
  { id: 67, name: 'script-generator', title: 'Dialogue Generation App', description: 'Generate scripts for presentations, videos, and podcasts.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/script-generator' },
  { id: 68, name: 'volt', title: 'Volt Virtual Card', description: 'Analyse and optimise energy consumption in power grids.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/volt' },
  { id: 69, name: 'biochem', title: 'BioChemAI Teaching Aid', description: 'AI tool for teaching biochemistry concepts.', category: Category.Education, url: 'https://ai-tools.techbridge.edu.gh/biochem' },
  { id: 70, name: 'genai', title: 'AUCDT GENAI Application Directory', description: 'Create stunning images, text, and music with generative models.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/genai' },
  { id: 71, name: 'lyrics', title: 'Patois Lyricist - Reggae Lyric Generator', description: 'Compose creative and original song lyrics in various styles.', category: Category.Development, url: 'https://ai-tools.techbridge.edu.gh/lyrics' },
  { id: 72, name: 'omniextract', title: 'OmniExtract - PDF Data Extractor', description: 'Extract structured data from unstructured documents and images.', category: Category.Analysis, url: 'https://ai-tools.techbridge.edu.gh/omniextract' },
];