import { Lesson } from "./types";

export const LESSONS: Lesson[] = [
  {
    id: 1,
    title: "Home Row - Left Hand (A S D F)",
    description: "Connect your muscle memory with your left hand's primary anchor row targets: A, S, D, and F.",
    keys: "asdf",
    icon: "🏠",
    practices: [
      "asdf asdf asdf asdf",
      "sad dad fasf dads",
      "asa sda faf sads",
      "dff ass sdd saff ddf"
    ]
  },
  {
    id: 2,
    title: "Home Row - Right Hand (J K L ;)",
    description: "Align your right hand on J, K, L, and semicolon. Always rest your right index finger on J.",
    keys: "jkl;",
    icon: "🏠",
    practices: [
      "jkl; jkl; jkl; jkl;",
      "jak jal kal; jalk",
      "jaj kdk lfl ;s;",
      "lass kals jass kaff"
    ]
  },
  {
    id: 3,
    title: "Home Row - Comprehensive Mastery",
    description: "Saturate home row coordinates. Master both hands typing together across the absolute center row.",
    keys: "asdfjkl;",
    icon: "⚡",
    practices: [
      "ask jak sad fads",
      "shall flash flask flaks",
      "salsa halls falls jals",
      "flask salad jads kals"
    ]
  },
  {
    id: 4,
    title: "Top Row - Left Hand Expansion (Q W E R T)",
    description: "Reach upwards from anchor row keys. Learn target structures for Q, W, E, R, and T.",
    keys: "qwert",
    icon: "🚀",
    practices: [
      "were wet wet tree were",
      "red tare rate wafer",
      "raw straw sweat tread",
      "water treats state safe"
    ]
  },
  {
    id: 5,
    title: "Top Row - Right Hand Expansion (Y U I O P)",
    description: "Reach upward with your right fingers to strike Y, U, I, O, and P accurately.",
    keys: "yuiop",
    icon: "🚀",
    practices: [
      "you you your output",
      "pour prior loyalty",
      "utility plot youth",
      "propitory trial write"
    ]
  },
  {
    id: 6,
    title: "Numeric Left Hand Sequence (1 2 3 4 5)",
    description: "Master keyboard numbers. Press 1 through 5 using progressive reaches from Home Row.",
    keys: "12345",
    icon: "🔢",
    practices: [
      "1 2 3 4 5 12345",
      "54321 15243 32541",
      "12 34 55 43 21 5",
      "15 sad 24 dad 35 fas"
    ]
  },
  {
    id: 7,
    title: "Numeric Right Hand Sequence (6 7 8 9 0)",
    description: "Type top right digits 6, 7, 8, 9, and 0 cleanly without looking down.",
    keys: "67890",
    icon: "🔢",
    practices: [
      "6 7 8 9 0 67890",
      "09876 68790 98076",
      "66 77 88 99 00 6",
      "jalk 678 lads 90 ;s"
    ]
  },
  {
    id: 8,
    title: "Bottom Row - Left Hand Pivot (Z X C V)",
    description: "Curl left hand fingers downward to learn bottom row mechanics: Z, X, C, and V.",
    keys: "zxcv",
    icon: "💪",
    practices: [
      "zap vex cat vet car",
      "zeal crest cave exact",
      "vext crack vest wax",
      "zapped active vertex caw"
    ]
  },
  {
    id: 9,
    title: "Bottom Row - Right Hand Pivot (B N M , .)",
    description: "Master bottom row keys B, N, M, comma, and period with clean finger targets.",
    keys: "bnm,.",
    icon: "💪",
    practices: [
      "ban numb bomb main man",
      "born norm corn barn bank",
      "name map coma comma dot.",
      "men back normal comma."
    ]
  },
  {
    id: 10,
    title: "Full Keyboard Championship Drill",
    description: "Strike all characters continuously across the keyboard and finalize your TUC qualification.",
    keys: "abcdefghijklmnopqrstuvwxyz",
    icon: "👑",
    practices: [
      "The quick brown fox jumps over the lazy dog.",
      "Pack my box with five dozen liquor jugs.",
      "All the world is a stage and all people play parts.",
      "Typing smoothly minimizes mistakes and maximizes speed."
    ]
  },
  {
    id: 11,
    title: "Numeric Keypad - Fast Data Entry (AI Era)",
    description: "Master the dedicated numeric keypad with the right hand for rapid IDs, prices, and dates - essential for fast data entry into AI tools and spreadsheets.",
    keys: "0123456789.-",
    icon: "🖩",
    inputMode: "numpad",
    practices: [
      "456 789 123 0.0",
      "2026-06-15 2025-12-31",
      "199.99 45.50 1000.00",
      "10293-84756 30219-58473"
    ]
  }
];

// A broad, varied bank of 1,000+ real English words (animals, food, nature, school,
// technology, sports, body, clothing, weather, emotions, transport, household,
// professions, colors/shapes, science, music, verbs, adjectives, places, time,
// abstract concepts, games) plus Techbridge/Ghana-themed terms. Selected uniformly
// at random regardless of difficulty (see GameTab.tsx).
export const GAME_WORDS = [
  "accordion", "accountant", "accra", "achievement", "actor", "adapter", "adventure", "adventurous",
  "afraid", "africa", "afternoon", "airplane", "airport", "album", "algebra", "amber",
  "ambition", "ambitious", "ambulance", "america", "amplifier", "angry", "ankle", "anniversary",
  "antarctica", "antelope", "anthem", "anxious", "apple", "application", "appointment", "april",
  "apron", "arcade", "archery", "architect", "arithmetic", "artery", "asia", "assignment",
  "astronaut", "atmosphere", "atom", "attic", "audience", "august", "australia", "author",
  "avalanche", "avatar", "back", "backpack", "bacteria", "badge", "baker", "baking",
  "balcony", "ballad", "banana", "barley", "barometer", "baseball", "basement", "basketball",
  "bathroom", "battery", "bay", "beach", "bear", "beautiful", "beaver", "bedroom",
  "beige", "belt", "benin", "berry", "bicep", "bicycle", "binder", "biologist",
  "biology", "bird", "bison", "blackboard", "blanket", "blender", "blizzard", "blouse",
  "bluetooth", "bonus", "boot", "bored", "bowling", "boxing", "bracelet", "brain",
  "brave", "brazil", "bread", "breeze", "breezy", "brilliant", "broccoli", "bronze",
  "brooch", "broom", "browser", "bucket", "buckle", "buffalo", "building", "bulldozer",
  "bumpy", "burger", "burgundy", "butcher", "butter", "button", "cabinet", "cable",
  "calculating", "calendar", "calf", "calm", "camel", "camera", "canada", "candle",
  "canoe", "canyon", "cape", "capital", "captain", "caravan", "cargo", "carnivore",
  "carpenter", "carpet", "carriage", "carrot", "cashier", "castle", "cat", "catalyst",
  "cave", "ceiling", "celebration", "cello", "century", "ceremony", "chalk", "challenge",
  "champion", "championship", "character", "charcoal", "charger", "charming", "checkpoint", "cheek",
  "cheerful", "cheese", "cheetah", "chef", "chemist", "chemistry", "cherry", "chest",
  "chilly", "chin", "china", "chip", "chorus", "chromosome", "cinnamon", "circle",
  "circuit", "clarinet", "classroom", "cleaning", "clever", "cliff", "climate", "climbing",
  "cloudy", "coach", "coast", "colander", "collar", "collarbone", "colossal", "compassion",
  "competition", "composer", "compound", "computer", "concert", "conductor", "confidence", "confident",
  "confused", "console", "content", "continent", "controller", "cookie", "cooking", "cooperation",
  "copper", "costume", "cotton", "counting", "countryside", "courage", "courageous", "cracker",
  "crane", "crayon", "cream", "creating", "creative", "creativity", "crescent", "cricket",
  "crimson", "crow", "crying", "cube", "cucumber", "curiosity", "curious", "current",
  "curriculum", "curry", "cursor", "curtain", "cycling", "cyclone", "cylinder", "cymbal",
  "dancer", "dancing", "database", "dawn", "deadline", "decade", "december", "decision",
  "dedication", "deer", "defeat", "defender", "degree", "delicate", "delighted", "delightful",
  "delta", "democracy", "denim", "dentist", "desert", "designing", "desktop", "detergent",
  "determination", "determined", "dew", "diagonal", "diamond", "diligent", "diploma", "director",
  "discipline", "discovering", "discovery", "discus", "dishwasher", "district", "diving", "doctor",
  "document", "dog", "dolphin", "donkey", "doorbell", "download", "dragon", "drawer",
  "drawing", "dreaming", "dress", "driver", "driveway", "drizzle", "drone", "drought",
  "drumstick", "duck", "dune", "dungeon", "durable", "duration", "dusk", "dustpan",
  "eagle", "earlobe", "earring", "earthquake", "ecosystem", "ecstatic", "editor", "egypt",
  "elbow", "electrician", "electron", "elegant", "element", "elephant", "embarrassed", "emerald",
  "energetic", "engineer", "england", "enormous", "ensemble", "enthusiastic", "enzyme", "equality",
  "equator", "eraser", "essay", "ethiopia", "europe", "evening", "evolution", "exam",
  "excited", "expedition", "experiment", "exploration", "exploring", "extraordinary", "eyebrow", "eyelash",
  "eyelid", "fabric", "failure", "fairytale", "falcon", "fantastical", "fantasy", "farmer",
  "fearless", "february", "fence", "fencing", "ferry", "festival", "finger", "fingernail",
  "firefighter", "firetruck", "fish", "fisherman", "fixing", "flamingo", "flannel", "flexible",
  "flood", "fog", "foggy", "folder", "folding", "football", "forearm", "forecast",
  "forehead", "forest", "forklift", "fortnight", "fountain", "fox", "fragile", "france",
  "freedom", "freight", "frequency", "friction", "friday", "frost", "frostbite", "frosty",
  "frustrated", "fungus", "furious", "gabon", "gale", "gambia", "garden", "garlic",
  "gene", "generosity", "generous", "gentle", "geography", "geometry", "germany", "geyser",
  "ghana", "gigantic", "ginger", "giraffe", "glacier", "gloomy", "glove", "goalkeeper",
  "goat", "golden", "goose", "gorgeous", "gorilla", "graceful", "grade", "gradient",
  "grammar", "grape", "grateful", "gratitude", "gravity", "gravy", "guitar", "habitat",
  "hailstorm", "hallway", "happy", "harbor", "hardware", "harmonica", "harmony", "hawk",
  "head", "headphone", "headset", "heart", "heatwave", "hedgehog", "heel", "helicopter",
  "helmet", "hemisphere", "hemline", "herbivore", "hero", "heron", "hexagon", "highway",
  "hippo", "history", "hockey", "holiday", "homework", "honest", "honesty", "honey",
  "hoodie", "hopeful", "horizon", "horizontal", "horse", "humid", "humidity", "hurdle",
  "hurricane", "hypothesis", "iceberg", "imagining", "impressive", "india", "indigo", "innovation",
  "inspiration", "instant", "integrity", "intelligent", "internet", "interval", "inventing", "iris",
  "island", "italy", "ivory", "jacket", "jade", "january", "japan", "javelin",
  "jealous", "jeans", "jersey", "jeweler", "journalist", "journey", "joyful", "joystick",
  "judge", "july", "jumping", "june", "jungle", "justice", "kangaroo", "kayak",
  "kenya", "kettle", "keyboard", "kidney", "kindness", "kingdom", "kitchen", "knee",
  "knight", "knuckle", "koala", "kumasi", "laboratory", "ladle", "lagoon", "lake",
  "lantern", "laptop", "laughing", "lavender", "lawyer", "leaderboard", "leadership", "league",
  "leather", "lecture", "legend", "lemon", "leopard", "lesson", "lettuce", "level",
  "liberia", "liberty", "librarian", "library", "ligament", "lightning", "linen", "lion",
  "listening", "literature", "liver", "lizard", "locomotive", "lonely", "loyalty", "lung",
  "lyric", "magenta", "magical", "magnetism", "magnificent", "mailbox", "mango", "marathon",
  "march", "marker", "maroon", "marsh", "marvelous", "massive", "mattress", "meadow",
  "measuring", "mechanic", "medal", "melody", "melon", "memory", "metropolis", "mexico",
  "microphone", "microscope", "microwave", "midfielder", "midnight", "miniature", "minivan", "mirror",
  "miserable", "mission", "mist", "mitten", "mixture", "modem", "molecule", "moment",
  "momentum", "monday", "monitor", "monkey", "monsoon", "moonlight", "mop", "morning",
  "morocco", "motivation", "motorcycle", "mountain", "mouse", "muffin", "mule", "muscle",
  "musician", "mutation", "mysterious", "mystery", "necklace", "nerve", "nervous", "network",
  "neutron", "nigeria", "nightgown", "noodle", "nostril", "notebook", "novelist", "november",
  "nucleus", "nurse", "oasis", "observation", "ocean", "octagon", "octave", "october",
  "officer", "olive", "omelet", "omnivore", "onion", "opportunity", "orange", "orchestra",
  "organ", "organism", "organizing", "otter", "oval", "overcast", "owl", "oyibi",
  "painter", "painting", "pajama", "pancake", "panda", "paragraph", "parasite", "parrot",
  "passenger", "passion", "password", "pasta", "patience", "patient", "pattern", "peaceful",
  "peach", "pelican", "pelvis", "pencil", "penguin", "peninsula", "pentagon", "pepper",
  "performer", "period", "perseverance", "pharmacist", "phone", "photosynthesis", "physicist", "physics",
  "piano", "pillow", "pilot", "pixel", "pizza", "planning", "plateau", "playful",
  "playlist", "pleasant", "plum", "plumber", "pocket", "pond", "popcorn", "porch",
  "potato", "prairie", "predator", "pressure", "pretzel", "printer", "prism", "processor",
  "producer", "professor", "program", "project", "protein", "proton", "proud", "province",
  "publisher", "pumpkin", "pupil", "purpose", "puzzle", "pyramid", "quarter", "quartet",
  "quest", "quiz", "rabbit", "raccoon", "railway", "rainbow", "rainy", "reaction",
  "reading", "rectangle", "reef", "referee", "refrigerator", "region", "relay", "relieved",
  "remarkable", "reminder", "repairing", "resilience", "respect", "respiration", "responsibility", "restless",
  "retina", "reward", "rhino", "rhythm", "rib", "rice", "riddle", "ring",
  "river", "robe", "robin", "robot", "rocket", "rough", "router", "rowboat",
  "rowing", "rugby", "running", "runway", "russia", "sad", "sailboat", "sailing",
  "salad", "salt", "sandal", "sandals", "sandwich", "satellite", "saturday", "sauce",
  "saxophone", "scanner", "scarf", "scarlet", "schedule", "scholarship", "science", "scissors",
  "scooter", "scoreboard", "sculptor", "seal", "seaport", "season", "selfish", "semester",
  "senegal", "sensor", "sentence", "september", "serious", "server", "shade", "shark",
  "sheep", "shelf", "shepherd", "shirt", "shoe", "shorts", "shoulder", "shouting",
  "shower", "sidekick", "sidewalk", "silk", "silver", "sincere", "singing", "single",
  "skating", "skiing", "skillet", "skillful", "skirt", "skull", "sleet", "sleeve",
  "slipper", "slippery", "smiling", "smooth", "snake", "sneaker", "snowfall", "soccer",
  "sock", "software", "solution", "solving", "sorting", "soundtrack", "soup", "spacecraft",
  "spain", "sparrow", "spatula", "speaker", "speaking", "spectacular", "spectrum", "spelling",
  "sphere", "spinach", "spine", "spiral", "sponge", "spreadsheet", "sprint", "square",
  "squirrel", "stadium", "stapler", "starlight", "stew", "stomach", "storage", "stork",
  "storm", "stormy", "strategy", "stream", "striker", "student", "stunning", "sturdy",
  "submarine", "suburb", "subway", "success", "sugar", "sunburn", "sunday", "sunlight",
  "sunrise", "sunset", "sunshine", "surfing", "surgeon", "surprised", "swamp", "swan",
  "sweater", "swimming", "syllabus", "symmetry", "symphony", "syrup", "tablet", "tailor",
  "takoradi", "talented", "tamale", "tambourine", "taxicab", "teacher", "teal", "teamwork",
  "telescope", "temperature", "tempo", "tender", "tendon", "tennis", "terminal", "terrace",
  "terrified", "textbook", "texture", "theory", "therapist", "thermometer", "thermostat", "thigh",
  "thinking", "thoughtful", "throat", "thumb", "thunder", "thunderstorm", "thursday", "tiger",
  "timetable", "timid", "tiny", "toaster", "toenail", "togo", "token", "tolerance",
  "tomato", "tongue", "tooth", "tornado", "tournament", "township", "tractor", "trailer",
  "tramway", "treasure", "tremendous", "triangle", "trolley", "trombone", "trophy", "trouser",
  "trumpet", "tuesday", "tundra", "turquoise", "turtle", "twilight", "typhoon", "uganda",
  "ukulele", "umpire", "uniform", "upload", "username", "vacation", "valley", "vanilla",
  "vein", "velocity", "velvet", "verse", "vertical", "vest", "victory", "village",
  "villain", "violet", "violin", "virus", "vision", "vocabulary", "volcano", "voltage",
  "vulture", "waffle", "wagon", "waiter", "walking", "walrus", "wardrobe", "washing",
  "watching", "waterfall", "wavelength", "website", "wednesday", "weekday", "weekend", "whale",
  "wheat", "whispering", "whistle", "whiteboard", "windy", "wireless", "wisdom", "wizard",
  "wolf", "wonderful", "wondering", "wool", "worried", "wrestling", "wrist", "writing",
  "xylophone", "yacht", "yogurt", "zambia", "zebra", "zigzag", "zipper", "techbridge",
  "university", "daniel", "twum", "ict", "system", "lecturer", "campus", "faculty",
  "graduation", "calculator", "birthday", "neighbor", "hospital", "hello", "world", "typing",
  "master", "practice",
];

export const REFERENCE_SPEEDTEXTS = [
  "Techbridge University College in Oyibi, Ghana, excels in providing robust technical certifications. Under the leadership of Daniel Twum, Head of ICT, the college is pioneering interactive student interfaces to build professional computer typing speeds. Practice remains the ultimate catalyst for muscle memory development.",
  "Computer keyboard mastery forms the fundamental bedrock of modern engineering productivity. When preparing educational builds, standard software compliance requires complete specifications under UK English conventions. Striking the character keys smoothly secures higher WPM indexes.",
  "Responsive web apps render inside accessible frames. For typing tasks, this means tracking character indexes in real time, validating errors seamlessly, and offering dark or high-contrast styles for low-vision students. Always align your index fingers on the home keys f and j.",
  "Capacitor bridges the web development ecosystem with native mobile distributions. Building iOS and Android packages can be completed via npx cap sync commands. Once archived via Android Studio or Xcode, developers upload release bundles to official App Stores for academic distribution."
];
