import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    // This is a fallback for development; in a real environment, the key should be set.
    // The UI will show a more user-friendly error if the key is missing at runtime.
    console.warn("API_KEY environment variable is not set. The application will not work without it.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY as string });

export const generateImage = async (prompt: string, resolution: string = '1024x1024'): Promise<string> => {
    if (!API_KEY) {
        throw new Error("Gemini API key is not configured. Please set the API_KEY environment variable.");
    }
    // All provided resolutions ('1024x1024', '512x512', etc.) are square.
    // The Imagen API takes an aspect ratio, not specific pixel dimensions.
    // We will use a '1:1' aspect ratio to match the requested square format.
    const aspectRatio = '1:1';

    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
                numberOfImages: 1,
                outputMimeType: 'image/jpeg',
                aspectRatio: aspectRatio,
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating image:", error);
        throw new Error("Failed to generate image. Check the browser console for more details.");
    }
};