allowBuilds:
  '@google/genai': true
  '@playwright/browser-chromium': true
  '@playwright/browser-firefox': true
  '@playwright/browser-webkit': true
  cypress: set this to true or false
  esbuild: true
  protobufjs: true
