allowBuilds:
  '@google/genai': set this to true or false
  '@playwright/browser-chromium': set this to true or false
  '@playwright/browser-firefox': set this to true or false
  '@playwright/browser-webkit': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
