import { jsPDF } from 'jspdf';
import autoTable, { UserOptions } from 'jspdf-autotable';
import { toPng } from 'html-to-image';
import type { PortfolioSummary, User } from '../types';

export const generateStatement = async (
  summary: PortfolioSummary,
  user: User,
  allocationChartId: string,
  performanceChartId: string
) => {
  // Fidelity-style styling
  const BRAND_COLOR = [20, 68, 48]; // Dark green / Teal-ish / Navy mix (let's use a Dark Navy for standard institution)
  const BRAND_NAVY = [0, 48, 114];  // institutional dark navy

  // Create new PDF document
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // -- Helpers --
  const formatCurrency = (val: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(val);

  const formatPercent = (val: number) =>
    new Intl.NumberFormat('en-US', { style: 'percent', minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(val / 100);

  const addHeader = (docInstance: jsPDF, title: string) => {
    // Top border bar
    docInstance.setFillColor(BRAND_NAVY[0], BRAND_NAVY[1], BRAND_NAVY[2]);
    docInstance.rect(0, 0, pageWidth, 8, 'F');

    // Brand Name
    docInstance.setFont('helvetica', 'bold');
    docInstance.setFontSize(20);
    docInstance.setTextColor(BRAND_NAVY[0], BRAND_NAVY[1], BRAND_NAVY[2]);
    docInstance.text('STOCKPULSE', margin, 25);
    
    // TechBridge Subtitle
    docInstance.setFont('helvetica', 'normal');
    docInstance.setFontSize(10);
    docInstance.setTextColor(100, 100, 100);
    docInstance.text('BY TECHBRIDGE STUDIO', margin, 30);

    // Title
    docInstance.setFontSize(18);
    docInstance.setTextColor(40, 40, 40);
    docInstance.text(title, margin, 45);

    // Account Details (Right aligned)
    docInstance.setFontSize(10);
    const dateStr = `Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
    const ownerStr = `Account Owner: ${user.name || user.email}`;
    docInstance.text(ownerStr, pageWidth - margin, 25, { align: 'right' });
    docInstance.text(dateStr, pageWidth - margin, 30, { align: 'right' });

    // Header divider
    docInstance.setDrawColor(200, 200, 200);
    docInstance.line(margin, 50, pageWidth - margin, 50);
  };

  const addFooter = (docInstance: jsPDF, pageNumber: number) => {
    docInstance.setFont('helvetica', 'normal');
    docInstance.setFontSize(8);
    docInstance.setTextColor(150, 150, 150);
    docInstance.text('Brokerage Statement generated by StockPulse.', margin, pageHeight - 10);
    docInstance.text(`Page ${pageNumber}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  };

  // ---------------------------------------------------------
  // PAGE 1: ACCOUNT SUMMARY
  // ---------------------------------------------------------
  addHeader(doc, 'Portfolio Performance Statement');

  // Key Metrics
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(BRAND_NAVY[0], BRAND_NAVY[1], BRAND_NAVY[2]);
  doc.text('Account Value', margin, 65);
  
  doc.setFontSize(28);
  doc.setTextColor(0, 0, 0);
  doc.text(formatCurrency(summary.totalValue), margin, 78);

  const totalRet = summary.unrealizedPL;
  const totalRetPct = summary.unrealizedPLPercent;
  const isPos = totalRet >= 0;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Total Unrealised Return', margin, 88);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  if (isPos) doc.setTextColor(22, 163, 74); // Green
  else doc.setTextColor(220, 38, 38);       // Red
  doc.text(`${isPos ? '+' : ''}${formatCurrency(totalRet)} (${isPos ? '+' : ''}${formatPercent(totalRetPct)})`, margin, 95);

  // Capture charts if available
  let yPos = 110;
  
  try {
    const allocEl = document.getElementById(allocationChartId);
    const perfEl = document.getElementById(performanceChartId);
    const isDark = document.documentElement.classList.contains('dark');
    const bgColor = isDark ? '#030712' : '#ffffff';

    if (allocEl && perfEl) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14);
      doc.setTextColor(BRAND_NAVY[0], BRAND_NAVY[1], BRAND_NAVY[2]);
      doc.text('Asset Allocation', margin, yPos);
      doc.text('Performance History', pageWidth / 2 + 10, yPos);
      
      const allocImg = await toPng(allocEl, { backgroundColor: bgColor, pixelRatio: 2 });
      const perfImg = await toPng(perfEl, { backgroundColor: bgColor, pixelRatio: 2 });

      // Allocation Chart (Left)
      const chartWidth = (pageWidth - margin * 2 - 20) / 2;
      const allocProps = doc.getImageProperties(allocImg);
      const allocRatio = allocProps.width / allocProps.height;
      const allocHeight = chartWidth / allocRatio;
      
      // Performance Chart (Right)
      const perfProps = doc.getImageProperties(perfImg);
      const perfRatio = perfProps.width / perfProps.height;
      const perfHeight = chartWidth / perfRatio;

      doc.addImage(allocImg, 'PNG', margin, yPos + 5, chartWidth, allocHeight);
      doc.addImage(perfImg, 'PNG', pageWidth / 2 + 10, yPos + 5, chartWidth, perfHeight);
    }
  } catch (err) {
    console.error("Failed to capture charts for PDF:", err);
  }

  addFooter(doc, 1);

  // ---------------------------------------------------------
  // PAGE 2: HOLDINGS DETAIL
  // ---------------------------------------------------------
  doc.addPage();
  addHeader(doc, 'Holdings Detail');

  const tableBody = summary.positions.map(p => {
    const gl = p.unrealizedPL;
    const glPct = p.unrealizedPLPercent;
    return [
      p.ticker,
      p.shares.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 4 }),
      formatCurrency(p.avgCost),
      formatCurrency(p.currentPrice),
      formatCurrency(p.value),
      `${gl >= 0 ? '+' : ''}${formatCurrency(gl)} (${gl >= 0 ? '+' : ''}${formatPercent(glPct)})`
    ];
  });

  autoTable(doc, {
    startY: 60,
    head: [['Symbol', 'Quantity', 'Avg Cost', 'Current Price', 'Total Value', 'Unrealised G/L']],
    body: tableBody,
    theme: 'grid',
    headStyles: {
      fillColor: BRAND_NAVY,
      textColor: 255,
      fontStyle: 'bold',
      halign: 'right'
    },
    columnStyles: {
      0: { halign: 'left', fontStyle: 'bold' }, // Ticker
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right', fontStyle: 'bold' },
      5: { halign: 'right', fontStyle: 'bold' },
    },
    didParseCell: (data) => {
      // Color G/L column
      if (data.section === 'body' && data.column.index === 5) {
        const text = data.cell.text[0];
        if (text.startsWith('+')) {
          data.cell.styles.textColor = [22, 163, 74];
        } else if (text.startsWith('-')) {
          data.cell.styles.textColor = [220, 38, 38];
        }
      }
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251]
    },
    styles: {
      font: 'helvetica',
      fontSize: 9,
      cellPadding: 5,
    }
  });

  addFooter(doc, 2);

  // Save the document
  doc.save(`StockPulse_Statement_${new Date().toISOString().split('T')[0]}.pdf`);
};
