/**
 * Authentication Configuration
 *
 * Centralizes all authentication-related configuration from environment variables.
 *
 * SECURITY BEST PRACTICES:
 * 1. Never commit actual credentials to version control
 * 2. Use environment variables for all sensitive data
 * 3. Change default credentials in production
 * 4. Implement proper backend authentication for production
 * 5. Use HTTPS in production
 * 6. Implement rate limiting for failed login attempts
 *
 * @module config/auth.config
 */

/**
 * Check if running in development mode
 */
export const isDevelopment = process.env.NODE_ENV === 'development' ||
                             process.env.REACT_APP_DEV_MODE === 'true';

/**
 * Authentication credentials
 * These should be replaced with proper backend authentication in production
 */
export const AUTH_CONFIG = {
  // Dashboard login credentials
  username: process.env.REACT_APP_AUTH_USERNAME || 'admin',
  password: process.env.REACT_APP_AUTH_PASSWORD || 'changeme',

  // Admin panel password
  adminPassword: process.env.REACT_APP_ADMIN_PASSWORD || 'changeme',

  // Session configuration
  sessionTimeout: parseInt(process.env.REACT_APP_SESSION_TIMEOUT || '3600000', 10), // 1 hour default
  sessionStorageKey: process.env.REACT_APP_SESSION_STORAGE_KEY || 'analytics_session',
};

/**
 * Validate credentials against configured values
 *
 * @param {string} username - Username to validate
 * @param {string} password - Password to validate
 * @returns {boolean} True if credentials are valid
 */
export const validateCredentials = (username, password) => {
  // In development, warn about using default credentials
  if (isDevelopment && password === 'changeme') {
    console.warn('⚠️ WARNING: Using default credentials. Update .env file with secure credentials.');
  }

  return username === AUTH_CONFIG.username && password === AUTH_CONFIG.password;
};

/**
 * Validate admin password
 *
 * @param {string} password - Admin password to validate
 * @returns {boolean} True if password is valid
 */
export const validateAdminPassword = (password) => {
  // In development, warn about using default credentials
  if (isDevelopment && password === 'changeme') {
    console.warn('⚠️ WARNING: Using default admin password. Update .env file with secure password.');
  }

  return password === AUTH_CONFIG.adminPassword;
};

/**
 * Create a session token
 * In a real application, this should be handled by the backend
 *
 * @returns {Object} Session object
 */
export const createSession = () => {
  const session = {
    token: generateSessionToken(),
    createdAt: Date.now(),
    expiresAt: Date.now() + AUTH_CONFIG.sessionTimeout,
  };

  try {
    localStorage.setItem(AUTH_CONFIG.sessionStorageKey, JSON.stringify(session));
  } catch (error) {
    console.error('Failed to save session:', error);
  }

  return session;
};

/**
 * Check if current session is valid
 *
 * @returns {boolean} True if session is valid
 */
export const isSessionValid = () => {
  try {
    const sessionData = localStorage.getItem(AUTH_CONFIG.sessionStorageKey);
    if (!sessionData) return false;

    const session = JSON.parse(sessionData);
    return session.expiresAt > Date.now();
  } catch (error) {
    console.error('Failed to validate session:', error);
    return false;
  }
};

/**
 * Clear current session
 */
export const clearSession = () => {
  try {
    localStorage.removeItem(AUTH_CONFIG.sessionStorageKey);
  } catch (error) {
    console.error('Failed to clear session:', error);
  }
};

/**
 * Generate a random session token
 * In production, this should be generated by the backend
 *
 * @returns {string} Random session token
 */
const generateSessionToken = () => {
  const array = new Uint8Array(32);
  crypto.getRandomValues(array);
  return Array.from(array, byte => byte.toString(16).padStart(2, '0')).join('');
};

/**
 * Security validation checks
 * Run on application startup to warn about insecure configurations
 */
export const performSecurityChecks = () => {
  const warnings = [];

  // Check for default/weak credentials
  if (AUTH_CONFIG.password === 'changeme' || AUTH_CONFIG.password === 'admin' ||
      AUTH_CONFIG.password === 'password' || AUTH_CONFIG.password.length < 8) {
    warnings.push('Weak or default password detected');
  }

  if (AUTH_CONFIG.adminPassword === 'changeme' || AUTH_CONFIG.adminPassword === 'admin') {
    warnings.push('Default admin password detected');
  }

  // Check if running in production with dev credentials
  if (!isDevelopment) {
    if (AUTH_CONFIG.username === 'admin' && AUTH_CONFIG.password === 'analytics2024') {
      warnings.push('CRITICAL: Default development credentials in production environment!');
    }

    if (AUTH_CONFIG.adminPassword === 'admin2024') {
      warnings.push('CRITICAL: Default admin password in production environment!');
    }

    // Check for HTTPS in production
    if (window.location.protocol !== 'https:') {
      warnings.push('WARNING: Not using HTTPS in production environment');
    }
  }

  if (warnings.length > 0) {
    console.group('🔐 Security Warnings');
    warnings.forEach(warning => console.warn(`⚠️ ${warning}`));
    console.groupEnd();
  }

  return warnings;
};

export default AUTH_CONFIG;
