export const THEMES = {
  dark: {
    bg: "#0C0C0E",
    surface: "#14141A",
    surfaceAlt: "#1C1C26",
    border: "#2A2A3A",
    gold: "#C9A84C",
    goldLight: "#E8C96A",
    terracotta: "#D4694A",
    terracottaLight: "#E8886E",
    text: "#F0EDE6",
    textMuted: "#8A8799",
    textDim: "#4A4860",
    accent: "#7B6BDE",
    success: "#4CAF7D",
    warning: "#E8A44A",
    error: "#E85A4A",
  },
  light: {
    bg: "#FAF8F3",
    surface: "#FFFFFF",
    surfaceAlt: "#F3EFE6",
    border: "#E2DAC8",
    gold: "#A87D2A",
    goldLight: "#C9A84C",
    terracotta: "#C4552F",
    terracottaLight: "#D4694A",
    text: "#1A1614",
    textMuted: "#5A5248",
    textDim: "#A09890",
    accent: "#5B4BC4",
    success: "#2D8A57",
    warning: "#C47A2A",
    error: "#C4402A",
  },
  highContrast: {
    bg: "#000000",
    surface: "#0A0A0A",
    surfaceAlt: "#111111",
    border: "#FFFFFF",
    gold: "#FFD700",
    goldLight: "#FFE44D",
    terracotta: "#FF6633",
    terracottaLight: "#FF8866",
    text: "#FFFFFF",
    textMuted: "#CCCCCC",
    textDim: "#888888",
    accent: "#AA88FF",
    success: "#00FF88",
    warning: "#FFAA00",
    error: "#FF3333",
  },
} as const;

export const MODULES = [
  {
    id: "mas",
    code: "MAS",
    name: "Mannequin AI Studio",
    tagline: "Generate diverse, culturally authentic mannequin visuals",
    icon: "◈",
    color: "gold",
    status: "active",
    features: ["Body Diversity Engine", "Skin Tone Matrix (24+ tones)", "Cultural Pose Library", "Afrocentric Silhouette AI"],
    stats: { generated: "12,450", accuracy: "97.3%", diversity: "A+" },
  },
  {
    id: "fdg",
    code: "FDG",
    name: "Fashion Design Generator",
    tagline: "AI-powered garment creation with African textile DNA",
    icon: "✦",
    color: "terracotta",
    status: "active",
    features: ["Kente Pattern Generator", "Ankara Fusion Engine", "Adinkra Symbol Weaver", "Fabric Simulation AI"],
    stats: { designs: "8,920", patterns: "340+", styles: "West African · Pan-African" },
  },
  {
    id: "vto",
    code: "VTO",
    name: "Virtual Try-On",
    tagline: "See garments on bodies that look like yours",
    icon: "⬡",
    color: "accent",
    status: "active",
    features: ["Real-time Drape Simulation", "Multi-body-type Fitting", "Fabric Physics Engine", "AR Preview Mode"],
    stats: { tryon: "24,100", satisfaction: "94.2%", retention: "+38%" },
  },
  {
    id: "fabricforge",
    code: "FF",
    name: "FabricForge",
    tagline: "Analyse, source, and sustainably select African textiles",
    icon: "◎",
    color: "success",
    status: "active",
    features: ["Textile DNA Recognition", "Artisan Sourcing Network", "Sustainability Score", "WACS-Certified Fabrics"],
    stats: { fabrics: "1,200+", artisans: "450", countries: "22 African nations" },
  },
  {
    id: "designvault",
    code: "DV",
    name: "DesignVault",
    tagline: "Archive, version, and protect your creative portfolio",
    icon: "▣",
    color: "gold",
    status: "active",
    features: ["Blockchain IP Protection", "Version Control for Designs", "Collaboration Workspace", "Export to Production"],
    stats: { designs: "45,000+", protected: "100%", formats: "SVG · PDF · DXF · AI" },
  },
  {
    id: "fashionacademy",
    code: "FA",
    name: "FashionAcademy",
    tagline: "Africa's premier AI-powered fashion education platform",
    icon: "◉",
    color: "terracotta",
    status: "beta",
    features: ["12-Module Curriculum", "African Fashion History", "AI Design Mentor", "Industry Certification"],
    stats: { students: "3,200+", modules: "12", cert: "WACS Accredited" },
  },
  {
    id: "iam",
    code: "IAM",
    name: "Identity & Access",
    tagline: "Role-based access control and user management",
    icon: "⬟",
    color: "accent",
    status: "active",
    features: ["RBAC Engine", "OAuth2 / JWT Auth", "MFA Support", "Session Management"],
    stats: { roles: "7", security: "OWASP A+", uptime: "99.97%" },
  },
  {
    id: "admin",
    code: "ADM",
    name: "Admin Console",
    tagline: "Platform governance, analytics, and audit logging",
    icon: "⬢",
    color: "error",
    status: "protected",
    features: ["Audit Log Trail", "User Management", "Revenue Analytics", "System Health Monitor"],
    stats: { logs: "Real-time", retention: "90 days", compliance: "GDPR + GhDP" },
  },
] as const;

export const CURRICULUM = [
  { module: 1, title: "Foundations of African Fashion", duration: "4 weeks", level: "Beginner" },
  { module: 2, title: "Textile Heritage & Symbolism", duration: "3 weeks", level: "Beginner" },
  { module: 3, title: "Pattern Cutting & Construction", duration: "6 weeks", level: "Intermediate" },
  { module: 4, title: "Draping on Diverse Bodies", duration: "4 weeks", level: "Intermediate" },
  { module: 5, title: "AI-Assisted Design Workflow", duration: "5 weeks", level: "Intermediate" },
  { module: 6, title: "Kente, Ankara & Adinkra Mastery", duration: "4 weeks", level: "Advanced" },
  { module: 7, title: "Sustainable Sourcing in Africa", duration: "3 weeks", level: "Advanced" },
  { module: 8, title: "Digital Fashion & Virtual Try-On", duration: "5 weeks", level: "Advanced" },
  { module: 9, title: "Fashion Business & African Markets", duration: "4 weeks", level: "Advanced" },
  { module: 10, title: "Brand Identity & Storytelling", duration: "3 weeks", level: "Advanced" },
  { module: 11, title: "Production & Manufacturing", duration: "4 weeks", level: "Expert" },
  { module: 12, title: "Capstone: Launch Your Collection", duration: "6 weeks", level: "Expert" },
] as const;

export const AUDIT_LOGS = [
  { id: "AUD-001", timestamp: "2025-01-15 09:14:22", user: "admin@mannequin.ai", action: "USER_CREATED", resource: "IAM", severity: "INFO" as const, ip: "41.66.102.14" },
  { id: "AUD-002", timestamp: "2025-01-15 09:22:07", user: "designer@tbuni.edu.gh", action: "DESIGN_EXPORTED", resource: "DesignVault", severity: "INFO" as const, ip: "197.251.67.88" },
  { id: "AUD-003", timestamp: "2025-01-15 10:05:41", user: "unknown", action: "LOGIN_FAILED", resource: "IAM", severity: "WARN" as const, ip: "185.220.101.42" },
  { id: "AUD-004", timestamp: "2025-01-15 10:31:18", user: "admin@mannequin.ai", action: "ROLE_MODIFIED", resource: "IAM", severity: "HIGH" as const, ip: "41.66.102.14" },
  { id: "AUD-005", timestamp: "2025-01-15 11:00:00", user: "student@fashionacademy.ai", action: "MODULE_COMPLETED", resource: "FashionAcademy", severity: "INFO" as const, ip: "154.72.198.22" },
];
